'use strict';var Gg=function(a,b,c){a.timeOfStartCall=(new Date).getTime();var d=c||Fa,e=d.document,f=a.nonce||Ia(d);f&&!a.nonce&&(a.nonce=f);if("help"==a.flow){var g=Ka("document.location.href",d);!a.helpCenterContext&&g&&(a.helpCenterContext=g.substring(0,1200));g=!0;if(b&&JSON&&JSON.stringify){var h=JSON.stringify(b);(g=1200>=h.length)&&(a.psdJson=h)}g||(b={invalidPsd:!0})}g=[a,b,c];d.GOOGLE_FEEDBACK_START_ARGUMENTS=g;h=a.serverUri||"//www.google.com/tools/feedback";var l=d.GOOGLE_FEEDBACK_START;if(a.forceNewHelpPanel){var q=
Kf(Af(e),"SCRIPT");f&&q.setAttribute("nonce",f);q.onload=function(){d.startHelpPanel({helpcenter:a.helpCenterPath.split("/")[1],apiKey:"testpage",locale:a.locale,enableSendFeedback:a.enableSendFeedback||!1,helpApiData:{helpApiConfig:a,productData:b,productWindow:c}})};Ee(q,Ud(Gd(new Fd(Dd,"https://www.gstatic.com/support/help/staging/main_frame/help_panel_staging_binary.js"))));e.body.appendChild(q)}else if(l)l.apply(d,g);else{g=h+"/load.js?";for(q in a)h=a[q],null==h||Pa(h)||(g+=encodeURIComponent(q)+
"="+encodeURIComponent(h)+"&");q=Kf(Af(e),"SCRIPT");f&&q.setAttribute("nonce",f);Ee(q,Mf(g));e.body.appendChild(q)}};w("userfeedback.api.startFeedback",Gg);var Hg=function(){this.j=this.h=this.s=this.modelName=this.l=this.g=this.ed="";this.C=this.m=this.u=!1};var Ig=chrome.i18n.getMessage("4163185390680253103"),Jg=chrome.i18n.getMessage("492097680647953484"),Kg=chrome.i18n.getMessage("2575016469622936324"),Lg=chrome.i18n.getMessage("128276876460319075"),Mg=chrome.i18n.getMessage("3326722026796849289"),Ng=chrome.i18n.getMessage("1018984561488520517"),Og=chrome.i18n.getMessage("8205999658352447129"),Pg=chrome.i18n.getMessage("5723583529370342957"),Qg=chrome.i18n.getMessage("1550904064710828958"),Rg=chrome.i18n.getMessage("5014364904504073524"),Sg=chrome.i18n.getMessage("2194670894476780934"),
Tg=chrome.i18n.getMessage("6614468912728530636"),Ug=chrome.i18n.getMessage("5910595154486533449"),Vg=chrome.i18n.getMessage("5363086287710390513"),Wg=chrome.i18n.getMessage("244647017322945605"),Xg=chrome.i18n.getMessage("5375576275991472719"),Yg=chrome.i18n.getMessage("4592127349908255218"),Zg=chrome.i18n.getMessage("843316808366399491"),$g=chrome.i18n.getMessage("5699813974548050528"),ah=chrome.i18n.getMessage("8515148417333877999"),bh=chrome.i18n.getMessage("1636686747687494376"),ch=chrome.i18n.getMessage("4148300086676792937"),
dh=chrome.i18n.getMessage("3219866268410307919"),eh=chrome.i18n.getMessage("9211708838274008657"),fh=chrome.i18n.getMessage("8706273405040403641"),gh=chrome.i18n.getMessage("4756056595565370923"),hh=chrome.i18n.getMessage("7876724262035435114"),ih=chrome.i18n.getMessage("5485620192329479690"),jh=chrome.i18n.getMessage("6963873398546068901"),kh=chrome.i18n.getMessage("3567591856726172993"),lh=chrome.i18n.getMessage("3239956785410157548");/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var mh={"* ARIA-CHECKED":!0,"* ARIA-COLCOUNT":!0,"* ARIA-COLINDEX":!0,"* ARIA-CONTROLS":!0,"* ARIA-DESCRIBEDBY":!0,"* ARIA-DISABLED":!0,"* ARIA-EXPANDED":!0,"* ARIA-GOOG-EDITABLE":!0,"* ARIA-HASPOPUP":!0,"* ARIA-HIDDEN":!0,"* ARIA-LABEL":!0,"* ARIA-LABELLEDBY":!0,"* ARIA-MULTILINE":!0,"* ARIA-MULTISELECTABLE":!0,"* ARIA-ORIENTATION":!0,"* ARIA-PLACEHOLDER":!0,"* ARIA-READONLY":!0,"* ARIA-REQUIRED":!0,"* ARIA-ROLEDESCRIPTION":!0,"* ARIA-ROWCOUNT":!0,"* ARIA-ROWINDEX":!0,"* ARIA-SELECTED":!0,"* ABBR":!0,
"* ACCEPT":!0,"* ACCESSKEY":!0,"* ALIGN":!0,"* ALT":!0,"* AUTOCOMPLETE":!0,"* AXIS":!0,"* BGCOLOR":!0,"* BORDER":!0,"* CELLPADDING":!0,"* CELLSPACING":!0,"* CHAROFF":!0,"* CHAR":!0,"* CHECKED":!0,"* CLEAR":!0,"* COLOR":!0,"* COLSPAN":!0,"* COLS":!0,"* COMPACT":!0,"* COORDS":!0,"* DATETIME":!0,"* DIR":!0,"* DISABLED":!0,"* ENCTYPE":!0,"* FACE":!0,"* FRAME":!0,"* HEIGHT":!0,"* HREFLANG":!0,"* HSPACE":!0,"* ISMAP":!0,"* LABEL":!0,"* LANG":!0,"* MAX":!0,"* MAXLENGTH":!0,"* METHOD":!0,"* MULTIPLE":!0,
"* NOHREF":!0,"* NOSHADE":!0,"* NOWRAP":!0,"* OPEN":!0,"* READONLY":!0,"* REQUIRED":!0,"* REL":!0,"* REV":!0,"* ROLE":!0,"* ROWSPAN":!0,"* ROWS":!0,"* RULES":!0,"* SCOPE":!0,"* SELECTED":!0,"* SHAPE":!0,"* SIZE":!0,"* SPAN":!0,"* START":!0,"* SUMMARY":!0,"* TABINDEX":!0,"* TITLE":!0,"* TYPE":!0,"* VALIGN":!0,"* VALUE":!0,"* VSPACE":!0,"* WIDTH":!0},nh={"* USEMAP":!0,"* ACTION":!0,"* CITE":!0,"* HREF":!0,"* LONGDESC":!0,"* SRC":!0,"LINK HREF":!0,"* FOR":!0,"* HEADERS":!0,"* NAME":!0,"A TARGET":!0,
"* CLASS":!0,"* ID":!0,"* STYLE":!0};var oh={};
function ph(a){if(Ve&&!rf(9))return[0,0,0,0];var b=oh.hasOwnProperty(a)?oh[a]:null;if(b)return b;65536<Object.keys(oh).length&&(oh={});var c=[0,0,0,0];b=qh(a,/\\[0-9A-Fa-f]{6}\s?/g);b=qh(b,/\\[0-9A-Fa-f]{1,5}\s/g);b=qh(b,/\\./g);b=b.replace(/:not\(([^\)]*)\)/g,"     $1 ");b=b.replace(/{[^]*/gm,"");b=rh(b,c,/(\[[^\]]+\])/g,2);b=rh(b,c,/(#[^\#\s\+>~\.\[:]+)/g,1);b=rh(b,c,/(\.[^\s\+>~\.\[:]+)/g,2);b=rh(b,c,/(::[^\s\+>~\.\[:]+|:first-line|:first-letter|:before|:after)/gi,3);b=rh(b,c,/(:[\w-]+\([^\)]*\))/gi,2);
b=rh(b,c,/(:[^\s\+>~\.\[:]+)/g,2);b=b.replace(/[\*\s\+>~]/g," ");b=b.replace(/[#\.]/g," ");rh(b,c,/([^\s\+>~\.\[:]+)/g,3);b=c;return oh[a]=b}function rh(a,b,c,d){return a.replace(c,function(e){b[d]+=1;return Array(e.length+1).join(" ")})}function qh(a,b){return a.replace(b,function(c){return Array(c.length+1).join("A")})};var sh={rgb:!0,rgba:!0,alpha:!0,rect:!0,image:!0,"linear-gradient":!0,"radial-gradient":!0,"repeating-linear-gradient":!0,"repeating-radial-gradient":!0,"cubic-bezier":!0,matrix:!0,perspective:!0,rotate:!0,rotate3d:!0,rotatex:!0,rotatey:!0,steps:!0,rotatez:!0,scale:!0,scale3d:!0,scalex:!0,scaley:!0,scalez:!0,skew:!0,skewx:!0,skewy:!0,translate:!0,translate3d:!0,translatex:!0,translatey:!0,translatez:!0},th=/[\n\f\r"'()*<>]/g,uh={"\n":"%0a","\f":"%0c","\r":"%0d",'"':"%22","'":"%27","(":"%28",")":"%29",
"*":"%2a","<":"%3c",">":"%3e"};function vh(a){return uh[a]}
var wh=function(a,b,c){b=Gc(b);if(""==b)return null;if(0==Hc("url(",b.substr(0,4))){if(!b.endsWith(")")||1<(b?b.split("(").length-1:0)||1<(b?b.split(")").length-1:0)||!c)a=null;else{a:{b=b.substring(4,b.length-1);for(var d=0;2>d;d++){var e="\"'".charAt(d);if(b.charAt(0)==e&&b.charAt(b.length-1)==e){b=b.substring(1,b.length-1);break a}}}a=c?(a=c(b,a))&&"about:invalid#zClosurez"!=Yd(a)?'url("'+Yd(a).replace(th,vh)+'")':null:null}return a}if(0<b.indexOf("(")){if(/"|'/.test(b))return null;for(a=/([\-\w]+)\(/g;c=
a.exec(b);)if(!(c[1].toLowerCase()in sh))return null}return b};function xh(a,b){a=Fa[a];return a&&a.prototype?(b=Object.getOwnPropertyDescriptor(a.prototype,b))&&b.get||null:null}function yh(a,b){return(a=Fa[a])&&a.prototype&&a.prototype[b]||null}
var zh=xh("Element","attributes")||xh("Node","attributes"),Ah=yh("Element","hasAttribute"),Bh=yh("Element","getAttribute"),Ch=yh("Element","setAttribute"),Dh=yh("Element","removeAttribute"),Eh=yh("Element","getElementsByTagName"),Fh=yh("Element","matches")||yh("Element","msMatchesSelector"),Gh=xh("Node","nodeName"),Hh=xh("Node","nodeType"),Ih=xh("Node","parentNode"),Jh=xh("HTMLElement","style")||xh("Element","style"),Kh=xh("HTMLStyleElement","sheet"),Lh=yh("CSSStyleDeclaration","getPropertyValue"),
Mh=yh("CSSStyleDeclaration","setProperty");function Nh(a,b,c,d){if(a)return a.apply(b);a=b[c];if(!d(a))throw Error("Clobbering detected");return a}function Oh(a,b,c,d){if(a)return a.apply(b,d);if(Ve&&10>document.documentMode){if(!b[c].call)throw Error("IE Clobbering detected");}else if("function"!=typeof b[c])throw Error("Clobbering detected");return b[c].apply(b,d)}function Ph(a){return Nh(zh,a,"attributes",function(b){return b instanceof NamedNodeMap})}
function Qh(a,b,c){try{Oh(Ch,a,"setAttribute",[b,c])}catch(d){if(-1==d.message.indexOf("A security problem occurred"))throw d;}}function Rh(a){Sh(a);return Nh(Jh,a,"style",function(b){return b instanceof CSSStyleDeclaration})}function Sh(a){if(!(a instanceof HTMLElement))throw Error("Not an HTMLElement");}function Th(a){Sh(a);return Nh(Kh,a,"sheet",function(b){return b instanceof CSSStyleSheet})}function Uh(a){return Nh(Gh,a,"nodeName",function(b){return"string"==typeof b})}
function Vh(a){return Nh(Hh,a,"nodeType",function(b){return"number"==typeof b})}function Wh(a){return Nh(Ih,a,"parentNode",function(b){return!(b&&"string"==typeof b.name&&b.name&&"parentnode"==b.name.toLowerCase())})}function Xh(a,b){return Oh(Lh,a,a.getPropertyValue?"getPropertyValue":"getAttribute",[b])||""}function Yh(a,b,c){Oh(Mh,a,a.setProperty?"setProperty":"setAttribute",[b,c])};var Zh=Ve&&10>document.documentMode?null:/\s*([^\s'",]+[^'",]*(('([^'\r\n\f\\]|\\[^])*')|("([^"\r\n\f\\]|\\[^])*")|[^'",])*)/g,$h={"-webkit-border-horizontal-spacing":!0,"-webkit-border-vertical-spacing":!0},ci=function(a,b,c){var d=[];a=ai(qc(a.cssRules));Wb(a,function(e){if(b&&!/[a-zA-Z][\w-:\.]*/.test(b))throw Error("Invalid container id");if(!(b&&Ve&&10==document.documentMode&&/\\['"]/.test(e.selectorText))){var f=b?e.selectorText.replace(Zh,"#"+b+" $1"):e.selectorText,g=d.push;e=bi(e.style,c);
if(-1!=f.indexOf("<"))throw Error("Selector does not allow '<', got: "+f);var h=f.replace(/('|")((?!\1)[^\r\n\f\\]|\\[\s\S])*\1/g,"");if(!/^[-_a-zA-Z0-9#.:* ,>+~[\]()=^$|]+$/.test(h))throw Error("Selector allows only [-_a-zA-Z0-9#.:* ,>+~[\\]()=^$|] and strings, got: "+f);a:{for(var l={"(":")","[":"]"},q=[],r=0;r<h.length;r++){var y=h[r];if(l[y])q.push(l[y]);else if(fd(l,y)&&q.pop()!=y){h=!1;break a}}h=0==q.length}if(!h)throw Error("() and [] in selector must be balanced, got: "+f);if(!(e instanceof
ee)){h="";for(var B in e)if(Object.prototype.hasOwnProperty.call(e,B)){if(!/^[-_a-zA-Z0-9]+$/.test(B))throw Error("Name allows only [-_a-zA-Z0-9], got: "+B);l=e[B];null!=l&&(l=Array.isArray(l)?Zb(l,ie).join(" "):ie(l),h+=B+":"+l+";")}e=h?new ee(h,de):ge}f=f+"{"+fe(e).replace(/</g,"\\3C ")+"}";g.call(d,new qe(f,pe))}});return se(d)},ai=function(a){return Yb(a,function(b){return b instanceof CSSStyleRule||b.type==CSSRule.STYLE_RULE})},ei=function(a,b,c){a=di("<style>"+a+"</style>");return null==a||
null==a.sheet?te:ci(a.sheet,void 0!=b?b:null,c)},di=function(a){if(Ve&&!rf(10)||"function"!=typeof Fa.DOMParser)return null;a=xe("<html><head></head><body>"+a+"</body></html>",null);return(new DOMParser).parseFromString(we(a),"text/html").body.children[0]},bi=function(a,b){if(!a)return ge;var c=document.createElement("div").style,d=fi(a);Wb(d,function(e){var f=Ye&&e in $h?e:e.replace(/^-(?:apple|css|epub|khtml|moz|mso?|o|rim|wap|webkit|xv)-(?=[a-z])/i,"");Dc(f,"--")||Dc(f,"var")||(e=Xh(a,e),e=wh(f,
e,b),null!=e&&Yh(c,f,e))});return new ee(c.cssText||"",de)},hi=function(a){var b=Array.from(Oh(Eh,a,"getElementsByTagName",["STYLE"])),c=Cc(b,function(e){return qc(Th(e).cssRules)});c=ai(c);c.sort(function(e,f){e=ph(e.selectorText);a:{f=ph(f.selectorText);for(var g=wc,h=Math.min(e.length,f.length),l=0;l<h;l++){var q=g(e[l],f[l]);if(0!=q){e=q;break a}}e=wc(e.length,f.length)}return-e});a=document.createTreeWalker(a,NodeFilter.SHOW_ELEMENT,null,!1);for(var d;d=a.nextNode();)Wb(c,function(e){Oh(Fh,d,
d.matches?"matches":"msMatchesSelector",[e.selectorText])&&e.style&&gi(d,e.style)});Wb(b,If)},gi=function(a,b){var c=fi(a.style),d=fi(b);Wb(d,function(e){if(!(0<=c.indexOf(e))){var f=Xh(b,e);Yh(a.style,e,f)}})},fi=function(a){Oa(a)?a=qc(a):(a=dd(a),lc(a,"cssText"));return a};var ii="undefined"!=typeof WeakMap&&-1!=WeakMap.toString().indexOf("[native code]"),ji=0,ki=function(){this.j=[];this.h=[];this.g="data-elementweakmap-index-"+ji++};ki.prototype.set=function(a,b){if(Oh(Ah,a,"hasAttribute",[this.g])){var c=parseInt(Oh(Bh,a,"getAttribute",[this.g])||null,10);this.h[c]=b}else c=this.h.push(b)-1,Qh(a,this.g,c.toString()),this.j.push(a);return this};
ki.prototype.get=function(a){if(Oh(Ah,a,"hasAttribute",[this.g]))return a=parseInt(Oh(Bh,a,"getAttribute",[this.g])||null,10),this.h[a]};ki.prototype.clear=function(){this.j.forEach(function(a){Oh(Dh,a,"removeAttribute",[this.g])},this);this.j=[];this.h=[]};var li=vg("goog.html.sanitizer.SafeDomTreeProcessor"),mi=!Ve||10<=Number(uf),ni=!Ve||null==document.documentMode,oi=function(){};var pi={APPLET:!0,AUDIO:!0,BASE:!0,BGSOUND:!0,EMBED:!0,FORM:!0,IFRAME:!0,ISINDEX:!0,KEYGEN:!0,LAYER:!0,LINK:!0,META:!0,OBJECT:!0,SCRIPT:!0,SVG:!0,STYLE:!0,TEMPLATE:!0,VIDEO:!0};var qi={A:!0,ABBR:!0,ACRONYM:!0,ADDRESS:!0,AREA:!0,ARTICLE:!0,ASIDE:!0,B:!0,BDI:!0,BDO:!0,BIG:!0,BLOCKQUOTE:!0,BR:!0,BUTTON:!0,CAPTION:!0,CENTER:!0,CITE:!0,CODE:!0,COL:!0,COLGROUP:!0,DATA:!0,DATALIST:!0,DD:!0,DEL:!0,DETAILS:!0,DFN:!0,DIALOG:!0,DIR:!0,DIV:!0,DL:!0,DT:!0,EM:!0,FIELDSET:!0,FIGCAPTION:!0,FIGURE:!0,FONT:!0,FOOTER:!0,FORM:!0,H1:!0,H2:!0,H3:!0,H4:!0,H5:!0,H6:!0,HEADER:!0,HGROUP:!0,HR:!0,I:!0,IMG:!0,INPUT:!0,INS:!0,KBD:!0,LABEL:!0,LEGEND:!0,LI:!0,MAIN:!0,MAP:!0,MARK:!0,MENU:!0,METER:!0,NAV:!0,
NOSCRIPT:!0,OL:!0,OPTGROUP:!0,OPTION:!0,OUTPUT:!0,P:!0,PRE:!0,PROGRESS:!0,Q:!0,S:!0,SAMP:!0,SECTION:!0,SELECT:!0,SMALL:!0,SOURCE:!0,SPAN:!0,STRIKE:!0,STRONG:!0,STYLE:!0,SUB:!0,SUMMARY:!0,SUP:!0,TABLE:!0,TBODY:!0,TD:!0,TEXTAREA:!0,TFOOT:!0,TH:!0,THEAD:!0,TIME:!0,TR:!0,TT:!0,U:!0,UL:!0,VAR:!0,WBR:!0};var ri={"ANNOTATION-XML":!0,"COLOR-PROFILE":!0,"FONT-FACE":!0,"FONT-FACE-SRC":!0,"FONT-FACE-URI":!0,"FONT-FACE-FORMAT":!0,"FONT-FACE-NAME":!0,"MISSING-GLYPH":!0},vi=function(a){a=a||new si;ti(a);this.g=id(a.g);this.u=id(a.G);this.j=id(a.L);this.s=a.D;Wb(a.C,function(b){if(!Dc(b,"data-"))throw new Rb('Only "data-" attributes allowed, got: %s.',[b]);if(Dc(b,"data-sanitizer-"))throw new Rb('Attributes with "%s" prefix are not allowed, got: %s.',["data-sanitizer-",b]);this.g["* "+b.toUpperCase()]=ui},
this);Wb(a.m,function(b){b=b.toUpperCase();if(-1==b.indexOf("-")||ri[b])throw new Rb("Only valid custom element tag names allowed, got: %s.",[b]);this.j[b]=!0},this);this.C=a.j;this.l=a.F;this.h=null;this.m=a.s};x(vi,oi);
var wi=function(a){return function(b,c){return(b=a(Gc(b),c))&&"about:invalid#zClosurez"!=Yd(b)?Yd(b):null}},si=function(){this.g={};Wb([mh,nh],function(a){Wb(dd(a),function(b){this.g[b]=ui},this)},this);this.h={};this.C=[];this.m=[];this.G=id(pi);this.L=id(qi);this.D=!1;this.O=ce;this.K=this.u=this.H=this.j=wd;this.F=null;this.l=this.s=!1},xi=function(a,b){return function(c,d,e,f){c=a(c,d,e,f);return null==c?null:b(c,d,e,f)}},yi=function(a,b,c,d){a[c]&&!b[c]&&(a[c]=xi(a[c],d))};si.prototype.ma=function(){return new vi(this)};
var ti=function(a){if(a.l)throw Error("HtmlSanitizer.Builder.build() can only be used once.");yi(a.g,a.h,"* USEMAP",zi);var b=wi(a.O);Wb(["* ACTION","* CITE","* HREF"],function(d){yi(this.g,this.h,d,b)},a);var c=wi(a.j);Wb(["* LONGDESC","* SRC","LINK HREF"],function(d){yi(this.g,this.h,d,c)},a);Wb(["* FOR","* HEADERS","* NAME"],function(d){yi(this.g,this.h,d,Ya(Ai,this.H))},a);yi(a.g,a.h,"A TARGET",Ya(Bi,["_blank","_self"]));yi(a.g,a.h,"* CLASS",Ya(Ci,a.u));yi(a.g,a.h,"* ID",Ya(Di,a.u));yi(a.g,a.h,
"* STYLE",Ya(a.K,c));a.l=!0},Ei=function(a,b){a||(a="*");return(a+" "+b).toUpperCase()},ui=function(a){return Gc(a)},Bi=function(a,b){b=Gc(b);return fc(a,b.toLowerCase())?b:null},zi=function(a){return(a=Gc(a))&&"#"==a.charAt(0)?a:null},Ai=function(a,b,c){return a(Gc(b),c)},Ci=function(a,b,c){b=b.split(/(?:\s+)/);for(var d=[],e=0;e<b.length;e++){var f=a(b[e],c);f&&d.push(f)}return 0==d.length?null:d.join(" ")},Di=function(a,b,c){return a(Gc(b),c)},Fi=function(a,b){var c=b.data;(b=Wh(b))&&"style"==
Uh(b).toLowerCase()&&!("STYLE"in a.u)&&"STYLE"in a.j&&(c=re(ei(c,a.h,Xa(function(d,e){return this.C(d,{NR:e})},a))));return document.createTextNode(c)},Gi=function(a){var b=(new si).ma();var c=!("STYLE"in b.u)&&"STYLE"in b.j;c="*"==b.l&&c?"sanitizer-"+Je():b.l;b.h=c;if(mi){c=a;if(mi){a=Gf(document,"SPAN");b.h&&"*"==b.l&&(a.id=b.h);b.m&&(c=di("<div>"+c+"</div>"),hi(c),c=c.innerHTML);c=xe(c,null);var d=document.createElement("template");if(ni&&"content"in d)Ce(d,c),d=d.content;else{var e=document.implementation.createHTMLDocument("x");
d=e.body;Ce(e.body,c)}c=document.createTreeWalker(d,NodeFilter.SHOW_ELEMENT|NodeFilter.SHOW_TEXT,null,!1);for(d=ii?new WeakMap:new ki;e=c.nextNode();){c:{var f=b;var g=e;var h=Vh(g);switch(h){case 3:g=Fi(f,g);break c;case 1:h=g;1==Vh(h)||Sb("Expected Node of type Element but got Node of type %s",Vh(h));g=f;f=h;if("TEMPLATE"==Uh(f).toUpperCase())g=null;else{h=Uh(f).toUpperCase();if(h in g.u)var l=null;else g.j[h]?l=document.createElement(h):(l=Gf(document,"SPAN"),g.s&&Qh(l,"data-sanitizer-original-tag",
h.toLowerCase()));if(l){var q=l,r=Ph(f);if(null!=r)for(var y=0;h=r[y];y++)if(h.specified){var B=g;var A=f,L=h,Q=L.name;if(Dc(Q,"data-sanitizer-"))B=null;else{var ka=Uh(A);L=L.value;var tb={tagName:Gc(ka).toLowerCase(),attributeName:Gc(Q).toLowerCase()},Eb={gv:void 0};"style"==tb.attributeName&&(Eb.gv=Rh(A));A=Ei(ka,Q);A in B.g?(B=B.g[A],B=B(L,tb,Eb)):(Q=Ei(null,Q),Q in B.g?(B=B.g[Q],B=B(L,tb,Eb)):B=null)}null!==B&&Qh(q,h.name,B)}g=l}else g=null}break c;default:zg(li,"Dropping unknown node type: "+
h),g=null}}if(g){if(1==Vh(g)&&d.set(e,g),e=Wh(e),f=!1,e)h=Vh(e),l=Uh(e).toLowerCase(),q=Wh(e),11!=h||q?"body"==l&&q&&(h=Wh(q))&&!Wh(h)&&(f=!0):f=!0,h=null,f||!e?h=a:1==Vh(e)&&(h=d.get(e)),h.content&&(h=h.content),h.appendChild(g)}else Hf(e)}d.clear&&d.clear();b=a}else b=Gf(document,"SPAN");0<Ph(b).length&&(a=Gf(document,"SPAN"),a.appendChild(b),b=a);b=(new XMLSerializer).serializeToString(b);b=b.slice(b.indexOf(">")+1,b.lastIndexOf("</"))}else b="";return xe(b,null)};if("undefined"!=typeof angular){var Hi=angular.module("chrome_18n",[]);chrome.runtime&&chrome.runtime.getManifest&&chrome.runtime.getManifest().default_locale&&Hi.directive("angularMessage",function(){return{restrict:"E",replace:!0,controller:["$scope",function(a){var b=this;this.gk=this.ph=null;a.dirForText=function(c){b.ph||(b.ph=chrome.i18n.getMessage("@@bidi_dir")||"ltr");b.gk||(b.gk=new Cg("rtl"==b.ph));var d=b.gk,e,f=e=0,g=!1;c=(c||"").split(Nd);for(var h=0;h<c.length;h++){var l=c[h];Ld.test(l)?
(e++,f++):Md.test(l)?g=!0:Kd.test(l)?f++:Od.test(l)&&(g=!0)}e=0==f?g?1:0:.4<e/f?-1:1;return-1==(0==e?d.g:e)?"rtl":"ltr"}}],compile:function(a,b){b=b.key;var c=null,d=document.createElement("amr");b&&!b.match(/^\d+$/)&&(b=chrome.i18n.getMessage(b),null==b&&d.setAttribute("id","missing"));if(b){var e=chrome.i18n.getMessage(b+"_ph");c=[];if(null!=e)for(c=e.split("\ue000"),e=0;e<c.length;++e)c[e]=c[e].replace(/^{{(.*)}}$/,'<amrp dir="{{dirForText($1)}}">{{$1}}</amrp>');c=chrome.i18n.getMessage(b,c)}else d.setAttribute("r",
"nokey");c?De(d,Gi(c)):(d.setAttribute("tl","false"),De(d,Gi(a.html())));a.replaceWith(d)}}})};var Ji=function(a,b){var c=this;this.m=b;this.g=a;this.g.top=a;this.C=[];this.l=!1;this.h=new Hg;this.g.videoSmoothnessRatings=this.Dm(Sg,Ng,Og,Pg,Qg,Rg);this.g.videoQualityRatings=this.Dm(Sg,Tg,Ug,Vg,Wg,Xg);this.g.audioQualityRatings=this.Dm(Sg,Yg,Zg,$g,ah,bh);this.C=[{value:"Bug",desc:Ig},{value:"FeatureRequest",desc:Jg},{value:"MirroringQuality",desc:Kg},{value:"Discovery",desc:Lg},{value:"Other",desc:Mg}];this.g.feedbackTypes=this.C;this.g.includeFineLogs=!0;this.g.feedbackType="Bug";this.g.sendFeedback=
this.CB.bind(this);this.g.cancel=this.Wu.bind(this);this.g.attachLogsClick=this.u.bind(this);this.g.viewLogs=this.F.bind(this);this.g.$watchGroup("videoSmoothness videoQuality audioQuality feedbackDescription comments feedbackType".split(" "),this.av.bind(this));this.g.sufficientFeedback=!1;this.g.$watch("attachLogs",this.u.bind(this));this.g.attachLogs=!0;this.s=Je();this.g.userEmail="";chrome.identity.getProfileUserInfo(function(d){c.g.userEmail=d.email;Ii(c)});this.g.yourAnswerText=lh;this.g.language=
chrome.i18n&&chrome.i18n.getUILanguage?chrome.i18n.getUILanguage():chrome.runtime.getManifest().default_locale;this.g.requestLogsInProgress=!1;this.g.mrVersion=chrome.runtime.getManifest().version};k=Ji.prototype;k.Dm=function(a){for(var b=[],c=1;c<arguments.length;c++)b.push(new Ki(c,arguments[c]));b.push(new Ki(0,arguments[0]));return b};k.Wu=function(){this.g.feedbackDescription&&!confirm(ch)||window.close()};
k.av=function(){var a=this.g.feedbackType;this.g.sufficientFeedback="MirroringQuality"==a?this.g.videoSmoothness||this.g.videoQuality||this.g.audioQuality||this.g.comments:"Discovery"==a?this.g.visibleInSetup||this.g.comments:!!this.g.feedbackDescription};
k.CB=function(){if(this.g.sufficientFeedback){var a=this.g.feedbackType,b="";"MirroringQuality"==a?(this.g.videoSmoothness&&(b+="\nVideo Smoothness: "+this.g.videoSmoothness),this.g.videoQuality&&(b+="\nVideo Quality: "+this.g.videoQuality),this.g.audioQuality&&(b+="\nAudio: "+this.g.audioQuality),this.g.projectedContentUrl&&(b+="\nProjected Content/URL: "+this.g.projectedContentUrl),this.g.comments&&(b+="\nComments: "+this.g.comments)):"Discovery"==a?(this.g.visibleInSetup&&(b+="\nChromecast Visible in Setup: "+
this.g.visibleInSetup),this.g.hasNetworkSoftware&&(b+="\nUsing VPN/proxy/firewall/NAS Software: "+this.g.hasNetworkSoftware),this.g.networkDescription&&(b+="\nNetwork Description: "+this.g.networkDescription),this.g.comments&&(b+="\nComments: "+this.g.comments)):b=this.g.feedbackDescription;a="Type: "+a+"\n\n"+b;this.g.sendDialogText=dh;this.g.okButton=kh;this.g.feedbackSent=!1;this.m.show({locals:{XR:this.g.feedbackSent,LS:this.g.sendDialogText,xz:this.g.okButton},scope:this.g,preserveScope:!0,bindToController:!0,
template:'<md-dialog id="feedback-confirmation"><md-dialog-content><div id="send-feedback-text">{{sendDialogText}}</div><md-dialog-actions><md-button class="md-raised md-primary"ng-disabled="!feedbackSent" ng-click="closeWindow()">{{okButton}}</md-button></md-dialog-actions></md-dialog-content></md-dialog>',controller:this.j});this.Zq(a,Date.now())}};k.Zq=function(a,b){var c=Date.now();!this.g.requestLogsInProgress||5E3<c-b?Li(this,a):setTimeout(this.Zq.bind(this),1E3,a,b)};
var Li=function(a,b){var c=0,d=function(f,g,h){h?f(!0):(a.g.sendDialogText=gh,Ii(a),g(Error("Failed to send")))},e=chrome.declarativeWebRequest?"MrTeamfood":"MRStable";(new Eg(function(){c++;return new Promise(function(f,g){var h=a.g.userEmail,l=a.h;f=d.bind(null,f,g);g=chrome.runtime.getManifest();Gg({productId:85561,bucket:e,flow:"submit",serverUri:"https://www.google.com/tools/feedback",allowNonLoggedInFeedback:!0,locale:g.default_locale,enableAnonymousFeedback:!h,report:{description:b},callback:f},
{version:g.version,description:g.description,user_email:h||"NA",logs:l.ed||"NA",external_logs:l.g||"NA",device_model:l.modelName||"NA",receiver_version:l.s||"NA",dash_report_url:l.l||"NA",cast_device_counts:l.h,dial_device_counts:l.j,mirroring_service_enabled:l.u,native_cast_mrp_enabled:l.m,native_dial_mrp_enabled:l.C})})},1E4,4)).start().then(function(){Jb("MediaRouter.Ui.Action.Feedback");a.g.sendDialogText=fh;a.g.feedbackSent=!0;Ii(a)},function(){a.g.sendDialogText=eh;a.g.feedbackSent=!0;Ii(a)})};
Ji.prototype.u=function(){var a=this;this.h=new Hg;this.g.attachLogs&&(this.g.requestLogsInProgress=!0,chrome.runtime.sendMessage(new Dg(this.s,"retrieve_log_data"),function(b){a.g.requestLogsInProgress=!1;a.h.ed=b.logs||"no extension";a.h.ed+="\n";a.h.ed+=b.mediaSinkServiceStatus||"no media sink service status from browser";a.h.ed+="\n";a.h.ed+=b.mediaRouterLogs||"no Media Router logs from the browser";b.castStreamingLogs&&(a.h.l=b.castStreamingLogs);b.castDeviceCounts&&(a.h.h=b.castDeviceCounts);
b.dialDeviceCounts&&(a.h.j=b.dialDeviceCounts);a.h.u=!!b.mirroringServiceEnabled;a.h.m=!!b.nativeCastMrpEnabled;a.h.C=!!b.nativeDialMrpEnabled;if(b=b.device)if(b.model&&(a.h.modelName=b.model),b.version&&(a.h.s=b.version),!a.l){var c=Je();a.l=!0;a.h.g=vb(b.ip,c,a.D.bind(a))}}))};
Ji.prototype.F=function(){this.g.logs=this.h.ed;this.g.logsHeader=hh;this.g.sendLogs=ih;this.g.fineLogsWarning=jh;this.g.okButton=kh;this.m.show({locals:{GR:this.g.attachLogs,ed:this.g.logs,hS:this.g.includeFineLogs,wS:this.g.logsHeader,MS:this.g.sendLogs,ZR:this.g.fineLogsWarning,xz:this.g.okButton},scope:this.g,preserveScope:!0,bindToController:!0,clickOutsideToClose:!0,template:'<md-dialog><md-dialog-content id="logs-dialog"><div class="subheading">{{logsHeader}}</div><div ng-show="includeFineLogs && attachLogs"id="feedback-fine-log-warning" class="informative">{{fineLogsWarning}}</div><pre>{{logs}}</pre><div class="send-logs"><md-checkbox type="checkbox" ng-model="attachLogs"ng-change="attachLogsClick()"><span>{{sendLogs}}</span></md-checkbox></div><md-dialog-actions><md-button class="md-raised md-primary"ng-click="closeDialog()">{{okButton}}</md-button></md-dialog-actions></md-dialog-content></md-dialog>',
controller:this.j})};Ji.prototype.D=function(a,b){this.l=!1;this.h.g="error"==a?"":b;this.g.attachLogs||(this.h.g="");Ii(this)};var Ii=function(a){a.g.$$phase||a.g.$apply()};Ji.prototype.j=function(a,b){a.closeWindow=function(){window.close()};a.closeDialog=function(){b.hide()}};Ji.prototype.j.$inject=["$scope","$mdDialog"];var Ki=function(a,b){this.id=a;this.desc=b;this.text=0==a?b:a+" ("+b+")"};
angular.module("feedbackApp","chrome_18n material.components.button material.components.checkbox material.components.dialog material.components.input material.components.radioButton".split(" ")).controller("FeedbackCtrl",["$scope","$mdDialog",Ji]);w("ng.safehtml.googSceHelper.isGoogHtmlType",function(a){return a&&a.ge?!0:!1});w("ng.safehtml.googSceHelper.isCOMPILED",function(){return!0});w("ng.safehtml.googSceHelper.unwrapAny",function(a){if(a instanceof Qd)return Rd(a).toString();if(a instanceof ve)return we(a).toString();if(a instanceof Xd)return Yd(a);if(a instanceof ee)return fe(a);if(a instanceof Id)return Jd(a).toString();throw Error();});
w("ng.safehtml.googSceHelper.unwrapGivenContext",function(a,b){if("html"==a)return we(b).toString();if("resourceUrl"==a||"templateUrl"==a)return Rd(b).toString();if("url"==a)return b instanceof Qd?Rd(b).toString():Yd(b);if("css"==a)return fe(b);if("js"==a)return Jd(b).toString();throw Error();});
