'use strict';var Ox={TAB:0,Wm:1,zt:2},Px=function(){return new zb("MediaRouter.CastStreaming.Session.Launch")},Qx=function(){return new Gb("MediaRouter.CastStreaming.Session.Length")},Rx=function(a){Kb("MediaRouter.CastStreaming.Start.Success",a,Ox)};var Sx=db("mr.mirror.cast.LogUploader"),Ux=function(a,b,c){Tx("raw_events.log.gz",a,b,c);return b?"https://crash.corp.google.com/samples?reportid=&q="+encodeURIComponent("UserComments='"+b+"'"):""},Tx=function(a,b,c,d){if(0==b.size)Sx.info("Trying to upload an empty file to Crash"),d&&d(null);else{var e=new FormData;e.append("prod","Cast");e.append("ver",chrome.runtime.getManifest().version);e.append(a,b);c&&e.append("comments",c);vx("https://clients2.google.com/cr/report",function(f){f=f.target;
var g=null;Fx(f)?(g=Hx(f),Sx.info("Upload to Crash succeeded: "+g)):Sx.info("Upload to Crash failed. HTTP status: "+f.Ca());d&&d(g)},"POST",e,void 0,3E4)}};var Vx=function(){this.g=0;em(this)},Xx=function(){Wx||(Wx=new Vx);return Wx},Yx=function(){var a=Xx(),b={fraction:.01,autoSubmitTimeLimitMillis:6048E5},c=b.autoSubmitTimeLimitMillis,d=Date.now();return a.g&&c&&d-a.g<c?!1:Math.random()<b.fraction};Vx.prototype.fb=function(){return"mirror.cast.LogUtils"};Vx.prototype.fc=function(){return[void 0,{lastAutoSubmitMillis:this.g}]};Vx.prototype.ec=function(){var a=cm(this);this.g=a&&a.lastAutoSubmitMillis||0};var Wx=null;db("mr.mirror.cast.LogUtils");var Zx={fL:"OFFER",jD:"ANSWER",cM:"PRESENTATION",tH:"GET_STATUS",VO:"STATUS_RESPONSE",oH:"GET_CAPABILITIES",ME:"CAPABILITIES_RESPONSE",UN:"RPC"};var $x=function(){this.capabilities=this.status=this.g=this.error=this.rpc=this.result=this.type=this.h=this.sessionId=null},cy=function(a){try{if("string"!==typeof a)throw SyntaxError("Cannot parse non-string as JSON");var b;ay(JSON.parse(a),function(d){b=by(d)},function(){throw Error("non-Object result from JSON parse");});return b}catch(d){var c=d instanceof SyntaxError?"JSON parse error: "+d.message:"Type coercion error: "+d.message}"string"==typeof a?a="a string: "+a:a instanceof ArrayBuffer?
(a=new Uint8Array(a),a="an ArrayBuffer whose base64 is "+btoa(String.fromCharCode.apply(null,a))):a="of invalid data type "+typeof a;throw Error(c+". Input was "+a);},by=function(a){var b=new $x;null!=a.sessionId&&(b.sessionId=String(a.sessionId));dy(a.seqNum,function(f){b.h=f},function(){throw Error('"seqNum" must be a number');});if("type"in a){for(var c=String(a.type).toUpperCase(),d=n(Object.keys(Zx)),e=d.next();!e.done;e=d.next())if(Zx[e.value]==c){b.type=c;break}if(!b.type)throw Error('not a known message "type"');
}"result"in a&&(b.result=String(a.result));if("rpc"in a){if("string"!==typeof a.rpc)throw Error('"rpc" must be a String containing a base64 payload');b.rpc=new Uint8Array([].concat(p(atob(a.rpc))).map(function(f){return f.charCodeAt(0)}))}ay(a.error,function(f){b.error=ey(f)},function(){throw Error('"error" must be an Object');});ay(a.answer,function(f){b.g=fy(f)},function(){throw Error('"answer" must be an Object');});ay(a.status,function(f){b.status=gy(f)},function(){throw Error('"status" must be an Object');
});ay(a.capabilities,function(f){b.capabilities=hy(f)},function(){throw Error('"capabilities" must be an Object');});return b},ay=function(a,b,c){void 0!==a&&(a instanceof Object?b(a):c())},dy=function(a,b,c){void 0!==a&&("number"!==typeof a?c():b(a))},iy=function(a,b,c){void 0!==a&&(a instanceof Array&&a.every(function(d){return"number"===typeof d})?b(a):c())},jy=function(a,b,c){void 0!==a&&(a instanceof Array?b(a.map(function(d){return String(d)})):c())},ky=function(){this.u=null;this.g=[];this.h=
[];this.j=this.l=this.m=null},fy=function(a){var b=new ky;dy(a.udpPort,function(c){b.u=c},function(){throw Error('"answer.udpPort" must be a number');});iy(a.sendIndexes,function(c){b.g=c},function(){throw Error('"answer.sendIndexes" must be an array of numbers');});iy(a.ssrcs,function(c){b.h=c},function(){throw Error('"answer.ssrcs" must be an array of numbers');});"IV"in a&&(b.m=String(a.IV));"receiverGetStatus"in a&&(b.l="true"==String(a.receiverGetStatus).toLowerCase());"castMode"in a&&(b.j=String(a.castMode));
return b},ly=function(){this.details=this.description=this.code=null},ey=function(a){var b=new ly;dy(a.code,function(c){b.code=c},function(){throw Error('"error.code" must be a number');});"description"in a&&(b.description=String(a.description));ay(a.details,function(c){b.details=c},function(){throw Error('"error.details" must be an Object');});return b},my=function(){this.h=this.g=null},gy=function(a){var b=new my;dy(a.wifiSnr,function(c){b.g=c},function(){throw Error('"status.wifiSnr" must be a number');
});iy(a.wifiSpeed,function(c){b.h=c},function(){throw Error('"status.wifiSpeed" must be an array of numbers');});return b},ny=function(){this.h=this.g=null},hy=function(a){var b=new ny;jy(a.mediaCaps,function(c){b.g=c},function(){throw Error('"capabilities.mediaCaps" must be an array');});if("keySystems"in a){a=a.keySystems;if(!(a instanceof Array))throw Error('"capabilities.keySystems" must be an array');b.h=a.map(function(c){var d;ay(c,function(e){d=oy(e)},function(){throw Error('"capabilities.keySystems" entries must be *Objects');
});return d})}return b},py=function(){this.h=this.m=this.u=this.l=this.s=this.g=this.C=this.codecs=this.initDataTypes=this.j=null},oy=function(a){var b=new py;"keySystemName"in a&&(b.j=String(a.keySystemName));jy(a.initDataTypes,function(c){b.initDataTypes=c},function(){throw Error('"capabilities.initDataTypes" must be an array');});jy(a.codecs,function(c){b.codecs=c},function(){throw Error('"capabilities.codecs" must be an array');});jy(a.secureCodecs,function(c){b.C=c},function(){throw Error('"capabilities.secureCodecs" must be an array');
});jy(a.audioRobustness,function(c){b.g=c},function(){throw Error('"capabilities.audioRobustness" must be an array');});jy(a.videoRobustness,function(c){b.s=c},function(){throw Error('"capabilities.videoRobustness" must be an array');});"persistentLicenseSessionSupport"in a&&(b.l=String(a.persistentLicenseSessionSupport));"persistentReleaseMessageSessionSupport"in a&&(b.u=String(a.persistentReleaseMessageSessionSupport));"persistentStateSupport"in a&&(b.m=String(a.persistentStateSupport));"distinctiveIdentifierSupport"in
a&&(b.h=String(a.distinctiveIdentifierSupport));return b};var qy=function(a){this.o=db("mr.mirror.cast.MessageDispatcher");this.l=a;this.g=null;this.h=new Map;this.j=0},ry=function(a,b,c){if(a.h.has(b))throw Error("Attempt to multiple-subscribe to the same response type: "+b);a.h.set(b,c);a.j=0;kb(a.o,"Added subscriber for "+b+"-type messages.");a.g||(a.g=gw(a.l),a.g.onMessage=a.u.bind(a))},sy=function(a,b){a.h.delete(b)&&kb(a.o,function(){return"Removed subscriber of "+b+"-type messages."});0==a.h.size&&a.g&&(a.g.dispose(),a.g=null)};
qy.prototype.sendMessage=function(a){return this.g?"RPC"==a.type?this.g.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.remoting"}):this.g.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.webrtc"}):Promise.reject(Error("Require at least one subscriber before sending messages."))};
var ty=function(a,b,c,d,e){var f=null,g=function(){sy(a,c);null!=f&&(clearTimeout(f),f=null)};try{ry(a,c,function(h){e(h)&&g()})}catch(h){e(null,h);return}f=setTimeout(function(){g();e(null,Error("timeout"))},d);a.sendMessage(b).catch(function(h){g();e(null,h)})};
qy.prototype.u=function(a){if(a&&"string"===typeof a.namespace_&&a.namespace_.startsWith("urn:x-cast:com.google.cast.")){do{var b=void 0;try{b=cy(a.data)}catch(d){b=d.message;break}if(b.type){var c=this.h.get(b.type);if(c)try{c(b);return}catch(d){b="Error thrown during delivery. Response was: "+(JSON.stringify(b)+". Error from subscriber callback was: ")+(d.message+".")}else b="Message was ignored: "+JSON.stringify(b)}else b="Message did not include response type: "+JSON.stringify(b)}while(0);10>
this.j?this.o.J(b):kb(this.o,b);++this.j}};var uy=function(){this.g=Promise.resolve(1)},wy=function(a,b,c){return vy(a,function(d){return d==b},c)},xy=function(a,b){var c=[3,4];return vy(a,function(d){return-1!=c.indexOf(d)},b)},yy=function(a,b){a.g=a.g.catch(function(){return 1});return vy(a,function(){return!0},b)},vy=function(a,b,c){var d,e,f=new Promise(function(g,h){d=g;e=h});a.g=a.g.then(function(g){if(!b(g))return e(Error("Operation requires a different starting checkpoint than "+g)),Promise.resolve(g);var h=new zy(g);try{var l=c(h)}catch(q){l=
Promise.reject(q)}return l.then(function(q){return d(q)},function(q){return e(q)}).then(function(){if(null===h.g)throw Error("A prior operation that started at "+(g+" did not complete."));return h.g})},function(g){e(g);throw g;});return f},zy=function(a){this.h=a;this.g=null},Ay=function(a,b){a.g="number"===typeof b?b:a.h};var By=chrome.cast.streaming,Cy=db("mr.mirror.cast.StreamingLaunchWorkflow"),Ey=function(a,b,c,d,e){this.O=a.sessionId;this.D=a.ai;this.X=a.bf;this.j=b;this.K=c;this.H=d;this.hb=Dy(e,"onAnswer",this.D);this.ca=Dy(e,"onSessionStop",this.D);this.o=Cy;this.F=new uy;this.C=this.G=this.s=this.h=this.g=this.m=this.u=this.l=null};
Ey.prototype.start=function(a,b,c){var d=this;if(!a&&!b)return Promise.reject(Error("No tracks to stream"));var e=a instanceof Fy,f=b instanceof Fy;(e&&b&&!f||f&&a&&!e)&&Sb("Mixing remoting and non-remoting tracks");return wy(this.F,1,function(g){d.l=a;d.u=b;d.m=c;d.o.info(function(){return"Launching streaming for "+Gy(d)+" to a "+(d.X+".")});return Hy(d).then(d.L.bind(d)).then(function(h){return Iy(d,h).then(function(l){d.hb();var q=Jy(d,l,h);d.g=Ky(d,d.g,q);d.h=Ky(d,d.h,q);if(!d.g&&!d.h)throw Error("Receiver did not select any offers from: "+
JSON.stringify(h));d.G=!!l.l;d.C=function(r,y){r==d.g?d.m.Rf("Audio stream (id="+r+") error: "+y):r==d.h&&d.m.Rf("Video stream (id="+r+") error: "+y)};By.rtpStream.onError.addListener(d.C);return Ly(d,l,q)})}).then(function(){d.o.info(function(){return"Launched streaming for "+Gy(d)});d.m.oh(d);Ay(g,2);return{Ju:d.g,EC:d.h}})})};
Ey.prototype.stop=function(){var a=this;return yy(this.F,function(b){if(!a.l&&!a.u)return Ay(b,1),Promise.resolve();a.o.info(function(){return"Stopping streaming for "+Gy(a)+"."});a.C&&(By.rtpStream.onError.removeListener(a.C),a.C=null);if(a.m){var c=a.m.ei();a.m=null}else c=Promise.resolve();return c.then(function(){a.g&&(By.rtpStream.stop(a.g),By.rtpStream.destroy(a.g),a.g=null);a.h&&(By.rtpStream.stop(a.h),By.rtpStream.destroy(a.h),a.h=null);a.s&&(By.udpTransport.destroy(a.s),a.s=null);a.ca();
a.o.info(function(){return"Stopped streaming for "+Gy(a)+"."});a.l=null;a.u=null;Ay(b,1)})})};
var My=function(a,b){var c=JSON.stringify(b);return Promise.all([a.g&&new Promise(function(d){return By.rtpStream.getRawEvents(a.g,c,d)}),a.h&&new Promise(function(d){return By.rtpStream.getRawEvents(a.h,c,d)})]).catch(function(d){a.o.error("Unexpected error when calling getRawEvents()",d);return[]}).then(function(d){return new Blob(d.filter(function(e){return!!e}),{type:"application/gzip"})})},Ny=function(a){return Promise.all([a.g&&new Promise(function(b){return By.rtpStream.getStats(a.g,b)}),a.h&&
new Promise(function(b){return By.rtpStream.getStats(a.h,b)})]).catch(function(b){a.o.error("Unexpected error when calling getStats()",b);return[]}).then(function(b){return Object.assign.apply(Object,[{}].concat(p(b.filter(function(c){return!!c}))))})},Gy=function(a){if(a.l&&a.u)var b="audio+video ";else if(a.l)b="audio-only ";else if(a.u)b="video-only ";else return"stopped";return a.l instanceof Fy||a.u instanceof Fy?b+"remoting":b+"streaming"},Hy=function(a){return new Promise(function(b){var c=
function(d,e,f){d&&!a.l&&(By.rtpStream.destroy(d),d=null);e&&!a.u&&(By.rtpStream.destroy(e),e=null);a.o.info(function(){return"Created Cast Streaming session: audioStreamId="+d+", videoStreamId="+e+"."});a.g=d;a.h=e;a.s=f;b()};a.l instanceof Fy||a.u instanceof Fy?By.session.create(null,null,c):By.session.create(a.l,a.u,c)})};
Ey.prototype.L=function(){for(var a=Uj(),b=Uj(),c=[],d=n([this.g,this.h]),e=d.next();!e.done;e=d.next())if(e=e.value)for(var f=e==this.g,g=f?127:96,h=f?Math.floor(499999*Math.random())+1:Math.floor(499999*Math.random())+500001,l=f?48E3:9E4,q=n(By.rtpStream.getSupportedParams(e)),r=q.next();!r.done;r=q.next())r=r.value,r.payload.payloadType=g,r.payload.maxLatency=this.j.maxLatencyMillis,r.payload.minLatency=this.j.minLatencyMillis,r.payload.animatedLatency=this.j.animatedLatencyMillis,r.payload.ssrc=
h,r.payload.clockRate=l,r.payload.aesKey=a,r.payload.aesIvMask=b,f?(r.payload.channels=2,r.payload.maxBitrate=this.j.audioBitrate,r.payload.maxFrameRate=100):(r.payload.minBitrate=this.j.minVideoBitrate,r.payload.maxBitrate=this.j.maxVideoBitrate,r.payload.maxFrameRate=this.j.maxFrameRate),c.push(new Oy(e,r));return c};
var Ky=function(a,b,c){b&&!c.some(function(d){return d.streamId==b})&&(a.o.J("Destroying RTP stream not selected by the receiver: id="+b),By.rtpStream.destroy(b),b=null);return b},Iy=function(a,b){return new Promise(function(c,d){for(var e=[],f=0;f<b.length;++f){var g=b[f].params,h={index:f,codecName:g.payload.codecName.toLowerCase(),rtpProfile:"cast",rtpPayloadType:g.payload.payloadType,ssrc:g.payload.ssrc,targetDelay:g.payload.animatedLatency,aesKey:g.payload.aesKey,aesIvMask:g.payload.aesIvMask,
timeBase:"1/"+g.payload.clockRate,receiverRtcpEventLog:a.j.enableLogging,rtpExtensions:["adaptive_playout_delay"]};a.j.dscpEnabled&&(h.receiverRtcpDscp=46);127==g.payload.payloadType?Object.assign(h,{type:"audio_source",bitRate:0<g.payload.maxBitrate?1E3*g.payload.maxBitrate:60*g.payload.maxFrameRate+g.payload.clockRate*g.payload.channels,sampleRate:g.payload.clockRate,channels:g.payload.channels}):Object.assign(h,{type:"video_source",renderMode:"video",maxFrameRate:Math.round(1E3*g.payload.maxFrameRate)+
"/1000",maxBitRate:1E3*g.payload.maxBitrate,resolutions:[{width:a.j.maxWidth,height:a.j.maxHeight}]});e.push(h)}var l=a.l instanceof Fy||a.u instanceof Fy?"remoting":"mirroring",q={type:"OFFER",sessionId:a.O,seqNum:pn(a.K),offer:{castMode:l,receiverGetStatus:!0,supportedStreams:e}};a.o.info(function(){return"Sending OFFER message: "+JSON.stringify(q)});ty(a.H,q,"ANSWER",1E4,function(r,y){if(null==r)d(y);else if("ok"==r.result&&r.g){if(r.h!=q.seqNum)return a.o.J("Ignoring ANSWER for OFFER with different seqNum: "+
JSON.stringify(r)),!1;((y=r.g.j)&&y!=l||!y&&"mirroring"!=l)&&a.o.error("Expected receiver to ANSWER with castMode="+l+", but got: "+y);kb(a.o,function(){return"Received ANSWER: "+JSON.stringify(r)});c(r.g)}else d(Error("Non-OK ANSWER received: "+JSON.stringify(r)));return!0})})},Jy=function(a,b,c){if(b.g.length!=b.h.length)return a.o.error("sendIndexes.length != ssrcs.length in ANSWER: "+JSON.stringify(b)),[];for(var d=[],e={},f=0;f<b.g.length;e={eg:e.eg},++f){var g=b.g[f];if(0>g||g>=c.length)return a.o.error("Receiver selected invalid index ("+
g+" < "+c.length+") in ANSWER: "+JSON.stringify(b)),[];e.eg=c[g];if(d.some(function(h){return function(l){return l.streamId==h.eg.streamId}}(e)))return a.o.error("Receiver selected same RTP stream twice in ANSWER: "+JSON.stringify(b)),[];e.eg.params.payload.feedbackSsrc=b.h[g];if(d.some(function(h){return function(l){return l.params.payload.feedbackSsrc==h.eg.params.payload.feedbackSsrc}}(e)))return a.o.error("Receiver provided same SSRC for two different RTP streams in ANSWER: "+JSON.stringify(b)),
[];d.push(e.eg)}return d},Ly=function(a,b,c){var d=null,e=function(){d&&(By.rtpStream.onStarted.removeListener(d),d=null)};return(new Promise(function(f,g){var h=b.u||2344;a.o.info(function(){return"Starting RTP streams to receiver at "+(a.D+":"+h)+(" for selected offers: "+JSON.stringify(c))});var l=a.s||-1;a.j.dscpEnabled&&(a.o.info("Enabled DSCP in sender."),By.udpTransport.setOptions(l,{DSCP:!0}));By.udpTransport.setDestination(l,{address:a.D,port:h});var q=new Set(c.map(function(y){return y.streamId}));
d=function(y){q.delete(y);0==q.size&&f()};By.rtpStream.onStarted.addListener(d);l=n(c);for(var r=l.next();!r.done;r=l.next())r=r.value,By.rtpStream.toggleLogging(r.streamId,a.j.enableLogging),By.rtpStream.start(r.streamId,r.params);setTimeout(function(){g(Error("Timeout: RTP streams failed to start."))},1E4)})).then(e).catch(function(f){e();throw f;})},Dy=function(a,b,c){return a&&b in a?function(){try{a[b](c)}catch(d){Cy.error("Error from testHooks."+b,d)}}:function(){}},Oy=function(a,b){this.streamId=
a;this.params=b},Fy=function(){};var Py=db("mr.mirror.cast.MediaRemoter"),Sy=function(a,b,c,d,e,f){this.C=a;this.H=Qy(b,this.C.Lb);this.K=new Ey(this.C.Lb,c,d,e,f);this.G=e;this.u=new uy;this.j=new Ry;this.F=new mojo.Binding(mojo.MirrorServiceRemoter,this,null);this.o=Py;this.D=this.g=this.m=this.l=this.L=null;this.h=!0;this.s=this.O.bind(this)},Vy=function(a,b,c){return wy(a.u,1,function(d){a.L=b;a.l=c;var e=a.F.createInterfacePtrAndBind();a.F.setConnectionErrorHandler(function(){a.o.info("Remoter mojo pipe connection error.");
Ty(a)});a.g=new mojo.MirrorServiceRemotingSourcePtr;var f=Gj(a.C.mediaSource||"");if(!f)throw Error("Failed to parse tab ID from source:\n          "+a.C.mediaSource);a.o.info("Connecting remoter to browser: tabId="+f);(pj.get("mr.ProviderManager")||null).onMediaRemoterCreated(f,e,mojo.makeRequest(a.g));a.g.ptr.setConnectionErrorHandler(function(){a.o.info("RemotingSource mojo pipe connection error.");Ty(a)});return Uy(a).then(function(){if(a.h)a.g.onSinkAvailable(a.H);Ay(d,2)})})},Ty=function(a){return yy(a.u,
function(b){a.g&&(a.g.ptr.reset(),a.g=null);var c=a.m;a.m=null;a.l=null;a.L=null;a.F.close();chrome.settingsPrivate.onPrefsChanged.hasListener(a.s)&&chrome.settingsPrivate.onPrefsChanged.removeListener(a.s);return new Promise(function(d){window.setTimeout(function(){Wy(a).then(function(){Ay(b,1);d();c&&c()})},250)})})};k=Sy.prototype;k.DB=function(a){Xy(this.j,a)};k.oh=function(a){this.l&&this.l.oh(a)};k.ei=function(){return this.l?this.l.ei():Promise.resolve()};
k.Rf=function(a,b){this.o.error("Error during streaming: "+a,b);if(this.g)this.g.onError();Ty(this)};
k.start=function(){var a=this,b=!1;this.o.info(function(){b=!0;return"Starting next media remoting session."});b&&Yy(this.j,function(c){return a.o.info(c)});Zy(this.j);wy(this.u,2,function(c){return(0,a.L)().then(function(d){a.m=d;ry(a.G,"RPC",function(e){if(e.rpc){var f=a.j;e=e.rpc;f.m&&(++f.C,f.h+=e.length,f.m(e))}});Ay(c,3)}).catch(function(d){return Wy(a).then(function(){Ay(c);throw d;})})}).then(function(){a.o.info("Remoting started successfully.")}).catch(function(c){a.o.error("Failed to start remoting",c);
a.g.onError()})};k.dC=function(a,b){var c=this;return wy(this.u,3,function(d){return c.K.start(a?new Fy:null,b?new Fy:null,c).then(function(e){$y(c.j,function(f){return c.G.sendMessage(f)},function(f){c.g.onMessageFromSink(f)});Ay(d,4);return{audio_stream_id:e.Ju||-1,video_stream_id:e.EC||-1}}).catch(function(e){return Wy(c).then(function(){Ay(d);throw e;})})}).catch(function(d){c.o.error("Failed to start remoting streams",d);Ty(c);return{audio_stream_id:-1,video_stream_id:-1}})};
k.stop=function(a){var b=this;xy(this.u,function(c){b.g.onStopped(a);return Wy(b).then(function(){b.o.info("Remoting stopped.");Ay(c,5);(0,b.m)().then(function(){return wy(b.u,5,function(d){if(b.g&&b.h)b.g.onSinkAvailable(b.H);Ay(d,2);return Promise.resolve()})}).catch(function(d){throw d;});b.m=null})}).catch(function(c){b.o.error("Failed to stop remoting: ",c);Ty(b)})};
k.qv=function(){null===this.D&&(this.D=yb(this.C.Lb.ai).then(function(a){return a.h||!1}));return this.D.then(function(a){return{rate:(a?1E7:5E6)/8}})};
var Wy=function(a){return a.K.stop().then(function(){sy(a.G,"RPC");az(a.j);bz(a.j)})},Uy=function(a){return new Promise(function(b){chrome.settingsPrivate.getPref("media_router.media_remoting.enabled",function(c){chrome.runtime.lastError?a.o.error("Encountered error getting media remoting pref: "+JSON.stringify(chrome.runtime.lastError)):c.type!=chrome.settingsPrivate.PrefType.BOOLEAN?a.o.error("Pref value not a boolean: "+JSON.stringify(c)):(a.h=!!c.value,a.o.info("Initializing mediaRemotingEnabled_ with value read from pref: "+
a.h));chrome.settingsPrivate.onPrefsChanged.hasListener(a.s)||chrome.settingsPrivate.onPrefsChanged.addListener(a.s);b()})})};
Sy.prototype.O=function(a){if(this.g){a=n(a);for(var b=a.next();!b.done;b=a.next())if(b=b.value,"media_router.media_remoting.enabled"==b.key){if(b.type!=chrome.settingsPrivate.PrefType.BOOLEAN){this.o.error("Pref value not a boolean: "+JSON.stringify(b));break}a=!!b.value;if(this.h==a)break;this.h=a;this.o.info("mediaRemotingEnabled_ changed to: "+this.h);if(this.h)this.g.onSinkAvailable(this.H);else this.g.onStopped(mojo.RemotingStopReason.USER_DISABLED);break}}};
var Qy=function(a,b){var c=new mojo.RemotingSinkMetadata;c.features=[];c.friendly_name=b.ZB||"";c.audio_capabilities=[];c.video_capabilities=[];var d=mojo.RemotingSinkAudioCapability,e=mojo.RemotingSinkVideoCapability,f=c.audio_capabilities,g=c.video_capabilities,h=b.bf||"";(a.g||[]).forEach(function(l){switch(l){case "audio":f.push(d.CODEC_BASELINE_SET);break;case "aac":f.push(d.CODEC_AAC);break;case "opus":f.push(d.CODEC_OPUS);break;case "video":g.push(e.CODEC_BASELINE_SET);break;case "4k":g.push(e.SUPPORT_4K);
break;case "h264":g.push(e.CODEC_H264);break;case "vp8":g.push(e.CODEC_VP8);break;case "vp9":h.startsWith("Chromecast Ultra")&&g.push(e.CODEC_VP9);break;case "hevc":h.startsWith("Chromecast Ultra")&&g.push(e.CODEC_HEVC);break;default:Py.info("Unknown mediaCap name: "+l)}});b.bf&&"Chromecast Ultra"==b.bf&&g.push(e.SUPPORT_4K);return c};Sy.prototype.estimateTransmissionCapacity=Sy.prototype.qv;Sy.prototype.stop=Sy.prototype.stop;Sy.prototype.startDataStreams=Sy.prototype.dC;Sy.prototype.start=Sy.prototype.start;
Sy.prototype.sendMessageToSink=Sy.prototype.DB;
var Ry=function(){this.m=this.u=this.g=null;this.D=this.h=this.C=this.j=this.s=0;this.l=null},Zy=function(a){a.g=[];cz(a,performance.now())},$y=function(a,b,c){a.u=b;a.m=c;a.g?(b=a.g,a.g=null,b.forEach(function(d){return Xy(a,d.data).then(d.FB,d.ar)})):cz(a,performance.now())},az=function(a){if(a.g){var b=Error("Stop before delivering pending message");a.g.forEach(function(c){return c.ar(b)});a.g=null}a.u=null;a.m=null},Xy=function(a,b){if(a.u){var c=btoa(String.fromCharCode.apply(null,b));++a.s;
a.j+=b.length;return a.u({type:"RPC",rpc:c})}return a.g?new Promise(function(d,e){a.g.push({data:b,FB:d,ar:e})}):Promise.reject(Error("RPC pipe not started"))},Yy=function(a,b){bz(a);a.l=setInterval(function(){if(a.g)var c=a.g.length+" messages are waiting to send.";else{c=performance.now();var d=(c-a.D)/1E3;d="Over the past "+d.toFixed(1)+" seconds, sent "+(a.s+" messages ("+Math.round(a.j/d)+" bytes/sec) and received ")+(a.C+" messages ("+Math.round(a.h/d)+" bytes/sec).");cz(a,c);c=d}b(c)},3E4)},
bz=function(a){null!=a.l&&(clearInterval(a.l),a.l=null)},cz=function(a,b){a.s=0;a.j=0;a.C=0;a.h=0;a.D=b};function dz(a){return a&&a.getAudioTracks()&&0<a.getAudioTracks().length?a.getAudioTracks()[0]:null}function ez(a){return a&&a.getVideoTracks()&&0<a.getVideoTracks().length?a.getVideoTracks()[0]:null};var fz=function(a,b,c,d,e){this.j=new Ey(a,b,c,d,void 0===e?null:e);this.o=db("mr.mirror.cast.MediaStreamer");this.u=new uy;this.l=this.h=this.g=this.m=null};fz.prototype.start=function(a,b){var c=this;return wy(this.u,1,function(d){c.m=a;c.g=dz(a);c.g&&"ended"==c.g.readyState&&(c.g=null);c.h=ez(a);c.h&&"ended"==c.h.readyState&&(c.h=null);if(!c.g&&!c.h)return Ay(d),Promise.reject(Error("No MediaStream tracks to stream."));c.l=b;return c.j.start(c.g,c.h,c.l).then(function(){return Ay(d,2)})})};
fz.prototype.stop=function(){var a=this;return yy(this.u,function(b){return a.j.stop().then(function(){a.g=null;a.h=null;a.m=null;a.l=null;Ay(b,1)})})};var gz=function(a){return wy(a.u,2,function(b){a.o.info("Suspending media streaming...");return a.j.stop().then(function(){a.o.info("Suspended media streaming.");Ay(b,3)})})};
fz.prototype.resume=function(){var a=this;return wy(this.u,3,function(b){a.g&&"ended"==a.g.readyState&&(a.g=null);a.h&&"ended"==a.h.readyState&&(a.h=null);if(!a.g&&!a.h)return Promise.reject(Error("Cannot resume: All tracks have ended."));a.o.info("Resuming media streaming...");return a.j.start(a.g,a.h,a.l).then(function(){a.o.info("Resumed media streaming.");Ay(b,2)})})};var hz=function(a,b,c){this.u=a;this.l=b;this.j=c;this.o=db("mr.mirror.cast.WifiStatusMonitor");this.g=null;this.h=[]};hz.prototype.start=function(){var a=this;null==this.g&&(kb(this.o,"Starting Wifi Status Monitoring."),this.h=[],ry(this.j,"STATUS_RESPONSE",function(b){return iz(a,b)}),this.g=setInterval(function(){return jz(a)},12E4),jz(this))};hz.prototype.stop=function(){null!=this.g&&(kb(this.o,"Stopping Wifi Status Monitoring."),clearInterval(this.g),this.g=null,sy(this.j,"STATUS_RESPONSE"))};
var iz=function(a,b){if(null!=a.g)if(b.status){var c={};null!=b.status.g&&(c.wifiSnr=b.status.g);null!=b.status.h&&(c.wifiSpeed=b.status.h[3]);0==Object.keys(c).length?a.o.J(function(){return"No status fields populated in response: "+JSON.stringify(b)}):(c.timestamp=Date.now(),30==a.h.length&&a.h.shift(),a.h.push(c),a.o.info(function(){return"Current Wifi status: "+JSON.stringify(c)}))}else a.o.J(function(){return"Ignoring response without status: "+JSON.stringify(b)})},jz=function(a){a.j.sendMessage({type:"GET_STATUS",
sessionId:a.u,seqNum:pn(a.l),get_status:["wifiSnr","wifiSpeed"]})};var kz=function(a,b,c,d){this.L=b.ai;this.H={extVersion:chrome.runtime.getManifest().version,extChannel:"public",mirrorSettings:wq(a),sender:navigator.userAgent||"UNKNOWN",receiverProductName:b.bf};this.G=c;this.F=d;this.l=this.h=this.C=this.m=this.u=this.s=this.j=null;this.g=[]};kz.prototype.oh=function(a){null!=this.h&&clearInterval(this.h);this.j=a;this.s=Date.now();this.h=setInterval(this.D.bind(this,a),9E5)};
kz.prototype.ei=function(){null!=this.h&&(clearInterval(this.h),this.h=null);if(null!=this.j){var a=this.D(this.j);this.j=null;return a}return Promise.resolve()};kz.prototype.Rf=function(a,b){null==this.u&&(this.u=Date.now(),"function"===typeof a?this.m=a():"string"===typeof a&&(this.m=a),b&&"string"===typeof b.stack&&(this.C=b.stack))};
var mz=function(a,b){return(null==a.j?Promise.resolve():a.D(a.j)).then(function(){var c=b.map(function(d){d=lz(a,d);var e=d.map(function(g){return g.ud}).filter(function(g){return null!=g}),f=["["];d.map(function(g){return g.Og}).forEach(function(g,h){0<h&&f.push(",");f.push(g)});f.push("]");return{ud:new Blob(e,{type:"application/gzip"}),Og:new Blob(f,{type:"application/json"})}});a.g=[];return c})};
kz.prototype.D=function(a){var b=this;if(null!=this.l)return this.l;var c=yb(this.L).then(function(d){d={receiverVersion:d.g,receiverConnected:d.l,receiverOnEthernet:d.h,receiverHasUpdatePending:d.j,receiverUptimeSeconds:d.u};Object.assign(d,b.H);var e=Date.now();Object.assign(d,{startTime:b.s,endTime:e,activity:Gy(a),receiverWifiStatus:Array.from(b.F.h)});b.s=e;null!=b.u&&(Object.assign(d,{streamingErrorTime:b.u,streamingErrorMessage:b.m,streamingErrorCause:b.C}),b.u=null,b.m=null,b.C=null);return d});
return(this.l=Promise.all([c.then(function(d){return My(a,d)}),c,Ny(a)]).then(function(d){var e=n(d);d=e.next().value;var f=e.next().value;e=e.next().value;b.g.push({ud:d,Og:new Blob([JSON.stringify(Object.assign({tags:f},e))],{type:"application/json"})});b.g=lz(b,b.G);b.l=null}))||Promise.resolve()};
var lz=function(a,b){b-=2;for(var c=[],d=a.g.length-1;0<=d;--d){b-=a.g[d].Og.size+1;if(0>b)break;c.push({ud:null,Og:a.g[d].Og});if(null!=a.g[d].ud){var e=a.g[d].ud.size;b>=e&&(c[c.length-1].ud=a.g[d].ud,b-=e)}}return c.reverse()};var nz=function(a,b,c,d){d=void 0===d?null:d;Tj.call(this,b);var e=b.Lb;this.D=e.sessionId;this.L=a;this.K=d;this.o=db("mr.mirror.cast.Session");this.s=new uy;this.C=new on("mirror.cast.SeqNumGenerator");this.m=new qy(b.id);this.u=new fz(e,this.L,this.C,this.m,this.K);this.l=null;this.g=new kz(a,e,c,new hz(this.D,this.C,this.m));this.F=null};t(nz,Tj);k=nz.prototype;
k.start=function(a){var b=this;return wy(this.s,1,function(c){var d=Px();return b.u.start(a,b).then(function(){b.u.j.G&&(b.g.F.start(),oz(b));d.end();b.F=Qx();Ay(c,2);return b})})};k.stop=function(){var a=this;return yy(this.s,function(b){a.F&&(a.F.end(),a.F=null);a.g.F.stop();return a.u.stop().then(function(){return a.l?Ty(a.l):Promise.resolve()}).then(function(){a.l=null;Ay(b,4)})})};
k.Yq=function(){var a=this,b={sessionId:this.D,seqNum:pn(this.C),type:"PRESENTATION",icons:[],title:Rj(this.Yc)};this.o.info("Sending session metadata update to receiver: "+this.D);this.m.sendMessage(b).catch(function(c){a.o.J("Failed to send activity to sink: "+c.message)})};k.oh=function(a){this.g.oh(a)};k.ei=function(){return this.g.ei()};k.Rf=function(a,b){this.g.Rf(a,b);this.o.error(a,b);this.stop()};
var pz=function(a,b){return mz(a.g,b)},oz=function(a){qz(a).then(function(b){(b.g||[]).includes("video")?rz(a,b):a.o.J(function(){return"Receiver incapable of Media Remoting: "+JSON.stringify(b)})}).catch(function(b){a.o.J("None/Invalid capabilites response. Media Remoting disabled.",b)})},qz=function(a){return new Promise(function(b,c){var d={type:"GET_CAPABILITIES",sessionId:a.D,seqNum:pn(a.C)};a.o.info(function(){return"Sending GET_CAPABILITIES message: "+JSON.stringify(d)});ty(a.m,d,"CAPABILITIES_RESPONSE",
3E4,function(e,f){if(null==e)return c(f),!0;if("ok"!=e.result||!e.capabilities)return c(Error("Bad response: "+JSON.stringify(e))),!0;if(e.h!=d.seqNum)return a.o.info(function(){return"Ignoring CAPABILITIES_RESPONSE with different seqNum: "+JSON.stringify(e)}),!1;kb(a.o,function(){return"Received CAPABILITIES_RESPONSE: "+JSON.stringify(e)});b(e.capabilities);return!0})})},rz=function(a,b){wy(a.s,2,function(c){var d=a.h.Lb.bf||"<UNKNOWN>";if(!d.startsWith("Chromecast")&&!d.startsWith("Eureka Dongle"))return a.o.J('HACK: Media Remoting disabled because the receiver model--"'+
(d+'" according to discovery--is not a Chromecast.')),Ay(c),Promise.resolve();a.l=new Sy(a.h,b,a.L,a.C,a.m,a.K);return Vy(a.l,a.O.bind(a),a).catch(function(e){a.o.error("Media Remoting start failed: "+e.message,e)}).then(function(){return Ay(c)})})};nz.prototype.O=function(){var a=this;return wy(this.s,2,function(b){return new Promise(function(c,d){gz(a.u).then(function(){Ay(b,3);a.G=!0;Jj(a);c(a.X.bind(a))}).catch(function(e){a.Rf("Failed to suspend MediaStreamer before starting remoting",e);d(e)})})})};
nz.prototype.X=function(){var a=this;return wy(this.s,3,function(b){return new Promise(function(c,d){a.u.resume().then(function(){Ay(b,2);a.G=!1;Jj(a);c()}).catch(function(e){a.Rf("Failed resume MediaStreamer after ending remoting mode",e);d(e)})})})};var sz=function(){Hj.call(this,"cast_streaming");this.m=this.D=this.H=this.L=this.l=null;this.ea=this.K="";this.ka=this.s=!1;this.wa=this.La.bind(this);this.O=this.X=this.hb=this.ca=this.u=null};t(sz,Hj);k=sz.prototype;k.qh=function(a){this.s=a||!1;this.ka=!0};k.getName=function(){return"cast_streaming"};
k.yl=function(a,b,c,d,e){var f=this;if(!this.s)return Hj.prototype.yl.call(this,a,b,c,d,e);this.M.info("Start mirroring on route "+a.id);if(!this.ka)return Vi(Error("Not initialized"));var g=new Promise(function(h,l){f.C().then(function(){if(Fj(b)&&c.shouldCaptureVideo)return mj(!1).then(function(q){f.ea=q})}).then(function(){return e?e(a).promise:a}).then(function(q){f.K=b;tz(f,q);var r=f.L.createInterfacePtrAndBind(),y=f.H.createInterfacePtrAndBind(),B=uz(q,c);vz(f,q,b,d);if(!f.l)throw new Zi("Error to get mirroring service host");
f.D=new mojo.MirroringCastMessageChannelPtr;f.ca=Px();f.l.start(B,r,y,mojo.makeRequest(f.D));f.u=new Tj(a,f.j.O.bind(f.j));Jj(f.u);wz(f,q,b);f.X=function(){return h(q)};f.O=l}).catch(function(q){f.M.error("Mirroring launch error: "+q);f.Kg(void 0===q.reason?9:q.reason);l(q)})});return Wi(g)};k.yi=function(a,b){return new nz(a,b,20969472,null)};k.Vh=function(){Rx(0)};k.Sh=function(){Rx(1)};k.nj=function(){Rx(2)};k.Th=function(){Jb("MediaRouter.CastStreaming.Session.End")};
k.Kg=function(a){Kb("MediaRouter.CastStreaming.Start.Failure",a,Yi)};k.Uh=function(){Jb("MediaRouter.CastStreaming.Stream.End")};
k.fk=function(a){var b=this;return this.s?Promise.resolve():(new Promise(function(c){return chrome.metricsPrivate.getIsCrashReportingEnabled(c)})).then(function(c){var d=c&&Yx(),e=[9351424];d&&e.push(20969472);return pz(a,e).then(function(f){var g=f[f.length-1];f=nm(f[0].ud).catch(function(h){b.M.error("Failed to persist events Blob.",h)});d&&0<g.ud.size?Ux(g.ud,void 0,b.yz.bind(b)):c&&Tx("stats.json",g.Og,void 0,void 0);return f})})};k.yz=function(a){if(a){a=Xx();var b=Date.now();a.g=b}};
k.xl=function(a){if(this.s)return ab();this.M.info("Received message to upload logs for "+a);return this.g?pz(this.g,[20969472]).then(function(b){b=n(b).next().value;return 0==b.ud.size?"":Ux(b.ud,a)}):Promise.resolve(xz(this,a))};
var xz=function(a,b){var c=window.localStorage.getItem("mr.temp.mirror.cast.Service.eventsBlob");if(null==c||1>c.length)c=null;else{for(var d=new Uint16Array(c.length),e=0;e<c.length;++e)d[e]=c.charCodeAt(e);c=d.buffer;d=(new Uint8Array(c,c.byteLength-1,1))[0];c=new Uint8Array(c,0,c.byteLength-(0==d?2:1));c=new Blob([c],{type:"application/gzip"})}if(null!=c&&0!=c.size)return nm(new Blob),a.M.info("Uploading saved logs for feedback."),Ux(c,b)};k=sz.prototype;
k.onError=function(a){this.O&&(this.O(a),this.X=this.O=null,this.Kg(9));this.M.info("Mirroring service error: "+a);this.C()};k.didStart=function(){this.X&&(this.X(),this.X=this.O=null);this.ca&&(this.ca.end(),this.ca=null);this.hb=Qx();Ej(this.K)?this.Vh():Fj(this.K)?this.Sh():Cj(this.K)&&this.nj()};k.didStop=function(){this.C()};k.send=function(a){if(this.m){var b=JSON.parse(a.jsonFormatData);kb(this.M,function(){return"Sending message: "+JSON.stringify(b)});this.m.sendMessage(a.jsonFormatData,{namespace:a.messageNamespace})}};
k.Az=function(a){if(a&&(a.namespace_===mojo.MirroringWebRtcNamespace||a.namespace_===mojo.MirroringRemotingNamespace)&&this.D){var b=new mojo.MirroringCastMessage;b.messageNamespace=a.namespace_;"string"!==typeof a.data?this.M.info("Received non-string as JSON"):(b.jsonFormatData=a.data,this.D.send(b))}};
var tz=function(a,b){a.L=new mojo.Binding(mojo.MirroringSessionObserver,a,null);a.H=new mojo.Binding(mojo.MirroringCastMessageChannel,a,null);a.m=gw(b.id);a.m.onMessage=a.Az.bind(a)},uz=function(a,b){var c=new mojo.MirroringSessionParameters;c.receiverAddress=new mojo.IPAddress;c.receiverAddress.addressBytes=a.Lb.ai.split(".").map(function(d){return parseInt(d,10)});c.receiverModelName=a.Lb.bf;a=yz(a.mediaSource);c.targetPlayoutDelay=zz(a);!b.shouldCaptureVideo||!b.shouldCaptureAudio||a&&"0"===a.searchParams.get("streamingCaptureAudio")?
c.type=b.shouldCaptureVideo?mojo.MirroringSessionType.VIDEO_ONLY:mojo.MirroringSessionType.AUDIO_ONLY:c.type=mojo.MirroringSessionType.AUDIO_AND_VIDEO;return c},zz=function(a){if(!a)return null;a=Number(a.searchParams.get("streamingTargetPlayoutDelayMillis"));return isNaN(a)||0>=a?null:new mojo.TimeDelta({microseconds:1E3*a})},yz=function(a){if(!a)return null;try{return new URL(a)}catch(b){return null}},vz=function(a,b,c,d){a.l=new mojo.MirroringServiceHostPtr;b=b.Lb.tabId||-1;Ej(c)?a.j.getMirroringServiceHostForTab(b,
mojo.makeRequest(a.l)):Fj(c)?a.j.getMirroringServiceHostForDesktop(-1,a.ea,mojo.makeRequest(a.l)):Cj(c)?(b=new mojo.Url,b.url=c,a.j.getMirroringServiceHostForOffscreenTab(b,d||"",mojo.makeRequest(a.l))):a.l=null},wz=function(a,b,c){Ej(c)&&!chrome.tabs.onUpdated.hasListener(a.wa)&&chrome.tabs.onUpdated.addListener(a.wa);(Ej(c)||Cj(c))&&Mj(a.u,b.Lb.tabId)};sz.prototype.La=function(a,b,c){Bj(14);this.u&&Oj(this.u,a,b,c)};
sz.prototype.C=function(){chrome.tabs.onUpdated.removeListener(this.wa);return this.s?this.ka?this.l?(this.l.ptr.reset(),this.D=this.l=null,this.m&&this.m.dispose(),this.m=null,this.L&&(this.L.close(),this.L=null),this.H&&(this.H.close(),this.H=null),Nj(this.j,this.u.h.id),this.u=null,this.ea=this.K="",this.hb&&(this.hb.end(),this.hb=null),this.Th(),Promise.resolve(!0)):Promise.resolve(!1):Promise.reject("Not initialized"):Hj.prototype.C.call(this)};
sz.prototype.jd=function(a,b,c,d,e,f){return this.s?Vi(Error("Mirroring service does not support updating stream")):Hj.prototype.jd.call(this,a,b,c,d,e,f)};sz.prototype.send=sz.prototype.send;sz.prototype.didStop=sz.prototype.didStop;sz.prototype.didStart=sz.prototype.didStart;sz.prototype.onError=sz.prototype.onError;var Az=new sz;yj("mr.mirror.cast.Service",Az);
