var n;Array.prototype.includes||(Array.prototype.includes=function(a,b){return 0<=this.indexOf(a,b)});NodeList.prototype[Symbol.iterator]||(NodeList.prototype[Symbol.iterator]=Array.prototype[Symbol.iterator]);HTMLCollection.prototype[Symbol.iterator]||(HTMLCollection.prototype[Symbol.iterator]=Array.prototype[Symbol.iterator]);const aa=Boolean,ba=Array.isArray,t=RegExp.prototype.test,ca=Array.prototype.includes;Array.prototype.concat.bind([]);
const da=Function.call.bind(Array.prototype.slice),fa=Function.apply.bind(Array.prototype.push),ha=Function.apply.bind(String.fromCharCode,null),u="undefined"==typeof browser;u&&(browser=chrome);const w=navigator.userAgent.includes("Edge/"),ia=navigator.userAgent.includes("Edg/"),x=navigator.userAgent.includes("Firefox/"),ja=navigator.userAgent.includes("OPR/"),ka=navigator.userAgent.includes("YaBrowser/");var y,la,D,ma,na,oa;
const pa=x?69:w?77:66,qa=x?220:150,ta=sa("tooltip_title"),ua=sa("tooltip_disabled"),va="\n"+sa("tooltip_text"),wa={16:"images/logo16.png",32:"images/logo32.png"},xa={16:"images/logo16x.png",32:"images/logo32x.png"},F=["127.0.0.1:1001","0.1.0.1:1001"],ya=u?"Chrome_RenderWidgetHostHWND":x?"MozillaWindowClass":w?"Windows.UI.Core.CoreWindow":null,za=/(?!)/,Aa=["main_frame","sub_frame"],Ba=["object","image"];var Ca=Ba.concat("xmlhttprequest",w?"other":[]),Da=Aa.concat(Ba,"xmlhttprequest","other");
const G=["*://*/*"],Ea=["ftp://*/*"],Fa=G.concat(Ea,"file:///*",u?"about:blank":[]),Ga=G.concat(u?"about:blank":[]),Ha=/\.([^.\\/]*?)(?:\.[0-9.]+)?$/,Ia=/^v(\d+)\.(\d+)(?:b(\d+))?\b/,Ja=browser.runtime.getManifest(),Ka=browser.runtime.getURL("captured.html"),La=browser.runtime.getURL("").slice(0,-1),Ma=browser.extension.getBackgroundPage().location.href,Na=ja||ka,Oa=u||w;var Pa=!x,Qa=u,Ra=Ja.permissions.includes("notifications")||null;
const Sa=t.bind(/^(?:chrome|about|chrome-extension|chrome-search|ms-browser-extension|ms-appx-web|moz-extension):/),Ta=t.bind(/^(?:Host|Origin|Referer|Cookie|User-Agent|Connection|DNT|Accept-Encoding|Sec-.+)$/i),Ua=t.bind(/^(?:application\/(?:json|x-javascript)|text\/(?:javascript|plain))$/),Va=t.bind(/^(HTM|HTML|CGI|PHP|ASP|ASPX|JSP|JSPX)$/i),Wa=t.bind(/^idmreg:|\bidman|\binternetdownloadmanager\b/i),Xa=t.bind(/^[GPTSDVACR]*$/),Ya=ca.bind([301,302,303,307,308]),Za=ca.bind([301,302,303]),$a=t.bind(/^(?:https?|socks[45])$/),
ab={direct:2,auto_detect:3,system:4,pac_script:5,fixed_servers:7},bb=[null,[115,111,112,113,114],[111,112,114],[112],[111],[111],[111]],cb=[null,[115,116,117,118,119,120,121,123],[114,113,113,115,116,117,118,122,119,121,120,123,112],[113],[111,113,112,114,115,116],[111,112,113],[]],db={16:1,17:2,18:4,45:8,46:16},eb={http:1,https:9,ftp:2,ftps:10,idmreg:12},fb={"text/html":"HTML|HTM","text/css":"CSS","text/javascript":"JS|JSON","text/mspg-legacyinfo":"MSI|MSP","text/plain":"TXT|VTT|SRT|M3U|PLS|M3U8|MPD|F4M|TORRENT|BTT",
"text/srt":"SRT","text/vtt":"VTT|SRT","text/xml":"XML|MPD|F4M|TTML|TTML2","text/x-javascript":"JS|JSON","text/x-json":"JSON","application/dash+xml":"MPD","application/f4m+xml":"F4M|MPD","application/gzip":"GZ","application/javascript":"JS","application/json":"JSON","application/msword":"DOC|DOCX|DOT|DOTX","application/octet-stream-m3u8":"M3U8","application/pdf":"PDF","application/torrent":"TORRENT|BTT","application/ttaf+xml":"DFXP","application/ttml+xml":"TTML|TTML2","application/vnd.apple.mpegurl":"M3U8",
"application/zip":"ZIP","application/x-7z-compressed":"7Z","application/x-aim":"PLJ","application/x-bittorrent":"TORRENT|BTT","application/x-chrome-extension":"CRX","application/x-compress":"Z","application/x-compress-7z":"7Z","application/x-compressed":"ARJ","application/x-dosexec":"EXE","application/x-gtar":"TAR","application/x-gzip":"GZ","application/x-gzip-compressed":"GZ","application/x-javascript":"JS","application/x-mpegurl":"M3U8","application/x-msdos-program":"EXE|DLL","application/x-msi":"MSI",
"application/x-msp":"MSP","application/x-ole-storage":"MSI|MSP","application/x-rar":"RAR","application/x-rar-compressed":"RAR","application/x-sdlc":"EXE|SDLC","application/x-shockwave-flash":"SWF","application/x-silverlight-app":"XAP","application/x-subrip":"SRT","application/x-tar":"TAR","application/x-zip":"ZIP","application/x-zip-compressed":"ZIP","video/3gpp":"3GP|3GPP","video/3gpp2":"3GP|3GPP","video/avi":"AVI","video/f4f":"F4F","video/f4m":"F4M","video/flv":"FLV","video/mp2t":"TS|TSV|M3U8",
"video/mp4":"MP4|M4V|M4S","video/mpeg":"MPG|MPEG","video/mpegurl":"M3U|M3U8","video/mpg4":"MP4|M4V","video/msvideo":"AVI","video/quicktime":"MOV|QT","video/vnd.mpeg.dash.mpd":"MPD","video/webm":"WEBM","video/x-flash-video":"FLV","video/x-flv":"FLV","video/x-mp4":"MP4|M4V","video/x-mpegurl":"M3U|M3U8","video/x-mpg4":"MP4|M4V","video/x-ms-asf":"ASF","video/x-ms-wmv":"WMV","video/x-msvideo":"AVI","audio/3gpp":"3GP|3GPP","audio/3gpp2":"3GP|3GPP","audio/mp2t":"TS|TSA|M3U8","audio/mp3":"MP3","audio/mp4":"M4A|MP4|M4S",
"audio/mp4a-latm":"M4A|MP4","audio/mpeg":"MP3","audio/mpeg4-generic":"M4A|MP4","audio/mpegurl":"M3U|M3U8","audio/webm":"WEBM","audio/wav":"WAV","audio/x-mpeg":"MP3","audio/x-mpegurl":"M3U|M3U8","audio/x-ms-wma":"WMA","audio/x-wav":"WAV","ilm/tm":"MP3","image/avif":"AVIF","image/gif":"GIF|GFA","image/icon":"ICO|CUR","image/jpg":"JPG|JPEG","image/jpeg":"JPG|JPEG","image/png":"PNG|APNG","image/tiff":"TIF|TIFF","image/vnd.microsoft.icon":"ICO|CUR","image/webp":"WEBP","image/x-icon":"ICO|CUR","flv-application/octet-stream":"FLV"};
function H(a,b,c,d,e,f,h){if(a){var g=["MSG#",a,"#",b,"#",c,"#",d];this.j=a;this.type=b;this.m=c;this.l=d;this.a=e||[];this.h=g;if(e)for(a=0;a<e.length;a++)g.push(":",e[a]||0);if(f)for(var l in f)if(e=f[l],null!=e)if(g.push(",",l,"="),e instanceof Array){a=g.length;b=0;for(var k of e)b=k instanceof Uint8Array?b+(h?gb(k=ha(k)):k.length):b+gb(k=k.toString()),g.push(k);g.splice(a,0,b,":")}else"string"==typeof e||e instanceof String?g.push(gb(e),":",e):e instanceof Blob?g.push(e.size,":",e):g.push(e)}else this.i=
new FileReader}function hb(){this.a=hb.prototype.g++}hb.prototype.g=1;function ib(a,b,c,d){this.id=a;this.port=b;c&&(this.b=c=c.toLowerCase(),this.c="iframe"==c);d&&(this.f=d)}ib.prototype.a=0;function jb(a,b,c){this.id=a+","+b;this.c=null==c||0>c?null:a+","+c}function kb(){}function lb(a){a.f||(a.h.push(";"),a.f=!0);return a.h.join("")}function mb(a){a.f||(a.h.push(";"),a.f=!0);return new Blob(a.h)}function nb(a,b,c){a.f?a.c(a):(b.J=c||0,b.step=0,a.i.onload=a.s.bind(a,b),ob(a,b,0,50))}
H.prototype.s=function(a){for(var b=this.i.result;;)switch(a.step){case 0:var c=b.split(",",2),d=c.shift().split(":",2),e=d.shift();if(!d.length){if(!c.length)return this.c(this);a.step=1}var f=e.length+1;d=e.split("#",6);if(5!=d.length||"MSG"!=d[0])return this.c(this);this.j=parseInt(d[1]);this.type=parseInt(d[2]);this.m=parseInt(d[3]);this.l=parseInt(d[4]);b=b.slice(f);a.J+=f;a.step++;break;case 1:d=b.split(",",2);e=d.shift();if(!d.length){d=b.split(";",2);if(2>d.length)return ob(this,a,b.length,
100);a.step=4}f=e.length+1;d=this.a=e.split(":");for(e=0;e<d.length;e++)c=d[e],d[e]=c.includes(".")?parseFloat(c):parseInt(c);b=b.slice(f);a.J+=f;a.step++;break;case 2:c=b.split(",",2);2>c.length&&(c=b.split(";",2));d=c.shift().split(":",2);var h=d.shift();f=h.length;e=!1;if(d.length)f++;else{if(!c.length)return ob(this,a,b.length,25);e=!0}d=h.split("=",3);if(2!=d.length)return this.c(this);c=parseInt(d[0]);d=parseInt(d[1]);a.J+=f;a.step++;if(e){this[c]=d;b=b.slice(f);a.step++;break}a.item=c;a.count=
d;b=a.count;f=a.J;a=a.slice(f,f+b);a.size==b?this.i.readAsText(a):this.c(this);return;case 3:return this[a.item]=b,a.J+=a.count,a.step++,ob(this,a,0,21);case 4:switch(b[0]){case ",":a.step=2;b=b.slice(1);break;case ";":a.step++;break;default:return this.c(this)}a.J++;break;case 5:this.f=!0;this.g(this);a.size>a.J&&(b=new H,b.g=this.g,b.c=this.c,nb(b,a,a.J));return}};function ob(a,b,c,d){var e=b.J;c=e+c;b.size>c?a.i.readAsBinaryString(b.slice(e,c+d)):a.c(a)}
function I(){var a=this.constructor.prototype;for(b in a)b.startsWith("_")||"constructor"==b||(this[b]=a[b].bind(this));this.ra=[];this.da=this.A=null;this.v=!1;this.S=0;this.$=null;this.c={};this.i={};this.a={};this.s={};this.b={};this.B={};this.f={};this.g={};this.R={};this.K={};this.h={};this.L={};this.L.Db=[];this.ya=0;this.ta=this.l=this.xa=!1;this.ma=!0;this.V=null;this.sa=this.wa=this.M=!1;this.Va=this.qa=this.Ta=1;this.P={};this.j=null;this.ka=1;this.Ca=0;this.D=this.C=null;this.ua=za;this.G=
[];this.H=this.m=null;this.U=Array(16);this.ca=0;this.va=null;this.la=this.ba=!1;for(a=1;a<bb.length;a++){var b=this.G[a]={};for(var c of bb[a])b[c]=za}u&&browser.browserAction.disable();w||browser.browserAction.setTitle({title:ta+va});browser.browserAction.setIcon({path:822083584>y||w?wa[16]:wa});browser.browserAction.setBadgeBackgroundColor({color:"#606060"});x&&browser.runtime.onInstalled.addListener(this.Za);browser.runtime.onMessage.addListener(this.$a);browser.browserAction.onClicked.addListener(this.Wa);
browser.windows.onCreated.addListener(this.Ma);browser.windows.onRemoved.addListener(this.Na);browser.windows.onFocusChanged.addListener(this.zb);browser.tabs.onActivated.addListener(this.qb);browser.tabs.onUpdated.addListener(this.tb);browser.tabs.onRemoved.addListener(this.sb);browser.tabs.onAttached&&browser.tabs.onAttached.addListener(this.rb);this.Pa();this.na();pb(this,!0)}function qb(){}qb.prototype=[];var J=qb.prototype;qb=null;n=I.prototype;n.Za=function(a){a.version=Ja.version;this.Sa=a};
n.$a=function(a,b){38==a[0]&&browser.tabs.remove(b.tab.id)};n.Wa=function(a){var b=a.id,c=this.h[b];rb(this,b,!c,!0);this.M&&(c?(this.Z(a.windowId),sb(this,b)):K(this,b))};function rb(a,b,c,d){if((a.h[b]=c)||d){a=(c?ua:ta)+va;d=c?xa:wa;if(822083584>y||w)d=d[16];w||browser.browserAction.setTitle({title:a,tabId:b});browser.browserAction.setIcon({path:d,tabId:b});browser.browserAction.setBadgeText({text:c?"X":"",tabId:b})}}
function tb(a,b){u&&a.l&&browser.downloads.setShelfEnabled(!b);if(b){u&&a.l&&a.I(3,browser.downloads.onCreated,a.Xa);u&&a.l&&a.I(3,browser.downloads.onDeterminingFilename,a.Ya);b=na?void 0:Da;const c=["blocking"],d=u&&!oa&&1207959552<=y?["extraHeaders"]:[];a.I(4,browser.webRequest.onBeforeRequest,a.La,{urls:Ea,types:Aa},c);a.I(4,browser.webRequest.onBeforeRequest,a.La,{urls:G,types:b},["requestBody"]);a.I(4,browser.webRequest.onBeforeSendHeaders,a.vb,{urls:G,types:b},["requestHeaders"].concat(c,d));
a.I(4,browser.webRequest.onHeadersReceived,a.xb,{urls:G,types:b},["responseHeaders"].concat(c));a.I(4,browser.webRequest.onResponseStarted,a.yb,{urls:G,types:b});a.I(4,browser.webRequest.onErrorOccurred,a.wb,{urls:G,types:b})}else a.Ba(3,4)}
n.Ka=function(a){browser.runtime.lastError;if(a){var b=a.value;a=ab[b.mode];var c,d;this.U.fill(void 0);if(5==a&&(d=b.pacScript))d.data&&5E4<d.data.length?a=4:(c=d.data)?(a=6,c=c.replace(/\blet\b/g,"var").replace(/,(?=(?:\s*\/\/.*?\n)*\s*[\]}])/g,"")):c=d.url,this.U.fill(!0);else if(7==a){b=b.rules;d=b.bypassList;c=L(this,b.singleProxy);if(!c){c=L(this,b.fallbackProxy);var e=L(this,b.proxyForHttp,1),f=L(this,b.proxyForHttps,9);b=L(this,b.proxyForFtp,2);e!=f||e!=b||e!=c&&c?(c=(e||"")+";"+(f||"")+";"+
(b||"")+";"+(c||""),++a):c=e}d&&d.length&&(c+=";"+d.join(","))}b=5>a?a.toString():c?a+":"+c:null;b!=this.m&&(this.m&&this.za(),this.m=b)}};function L(a,b,c){if(b){var d=b.scheme||"http",e="https"==d;a=a.U;c?a[c]=e:a.fill(e);if($a(d))return d+"://"+b.host+(b.port?":"+b.port:"")}}
function ub(a,b,c,d){if(b){var e=b.type;if("direct"==e)return"0";"socks"==e&&(e="socks5");if($a(e)){var f="1:"+e+"://"+b.host+":"+b.port;"socks5"==e&&b.proxyDNS&&(f+="#");c||d||!(c=a.H)||(c=c.substr(c.indexOf(";")+1||c.length));c&&(f+=";"+c);d&&f&&(a.H=f);return f}}}
n.za=J[J.length]=function vb(a,b){if(void 0===a){if((Pa||Qa)&&this.v){var d=this.C;d||(b="http://"+(this.A?(new URL(this.A.url)).host:F[0]),d=b+"/status/204+IDM");a=new XMLHttpRequest;a.timeout=1E3;a.onreadystatechange=vb.bind(this,a,b);a.open("GET",d,!0);a.send()}}else 4==a.readyState&&(204!=a.status?this.C=this.D=null:b&&(this.C=b+"/status/204+IDM",this.D=Pa&&this.$?b+"/client/"+this.$:null))};
function pb(a,b){var c=a.c,d=a.P={};browser.contextMenus.removeAll();for(var e=0;e<wb.length;e++){var f=wb[e];f[0]&&(x?b||c[f[1]]:1)&&(d[e]=browser.contextMenus.create({title:sa(f[2]),contexts:f[3].split(","),onclick:f[4].bind(a),documentUrlPatterns:f[5]||Fa,enabled:!0}))}}n.ja=function(a,b,c,d){var e=this.f;return b in e?e[b]:e[b]=new ib(b,a,c,d)};function xb(a,b){a=a.g;var c=b.id;a[c]!==b&&(a[c]=b,w&&(a[b.requestId]=b))}
function yb(a,b,c,d,e){if(N(b)){var f=b.frameId||0;var h=b.parentFrameId;var g=b.method&&b.id;d||(d=b.tabId);e||(e=b.url)}else f=b;var l=a.s[d+","+f];l||(l=new jb(d,f,h),a.s[l.id]=l);g?(l.g!=g&&(l.g=g,l.l=e,l.f=!1,l.b&&(l.b=e.startsWith(b.initiator||b.originUrl))),l.i="POST"==b.method):e&&(e.startsWith("about:blank")?f&&(l.b=!0):l.o=e);null!=c&&(l.h=c);return l}function zb(a,b){return a.s[b.tabId+","+b.frameId]}function Ab(a){var b=new hb;return a.B[b.a]=b}
function Bb(a,b){delete a.B[b instanceof hb?b.a:b]}function Eb(a,b){a=a.G;for(var c=1;c<a.length;c++){var d=a[c][101];if(d&&d.test(b))return c}return 0}
n.na=function(){var a=this.S%(F.length+1);if(a<F.length)this.A=a=new WebSocket("ws://"+F[a]+"/?cid="+Math.random().toString().substr(2,9),"plugin.v3.internetdownloadmanager.com"),a.onopen=this.pa,a.onclose=this.N,a.onmessage=this.pb,1==a.readyState?this.pa():3==a.readyState&&this.N();else if(w)this.N();else{this.da=a=browser.runtime.connectNative("com.tonec.idm");try{a.postMessage("")}catch(b){a=null}a?(a.onDisconnect.addListener(this.N),a.onMessage.addListener(this.cb),this.pa()):this.N()}};
n.pa=function(){this.v=!0;this.qa=1;var a=browser.i18n.getUILanguage().replace("_","-");"sr"==a&&(a+="-Cyrl-CS");var b=[15,41,Na?1028:1031,0],c={};c[112]=D;c[113]=la;c[114]=ya;c[125]=JSON.stringify(this.Sa);c[116]=a;O(this,2,1,Na?0:1024,b,c)};
n.N=function(){browser.runtime.lastError;this.A=this.da=null;this.v&&(this.v=!1,this.R={},tb(this,!1),this.Ba(1,2),this.M=!1,this.m=this.D=this.C=null,u&&browser.browserAction.disable());var a=++this.S,b=F.length+1,c=a/b;120>c&&(1==c&&this.ma&&this.Aa(),!a||a%b?this.na():window.setTimeout(this.na,5E3*c))};n.pb=function(a){var b=new H;b.g=this.Ia;b.c=this.N;nb(b,a.data)};n.cb=function(a){var b=new H;b.g=this.Ia;b.c=this.N;nb(b,new Blob([a]))};
function O(a,b,c,d,e,f,h){if(!a.v)return!1;var g=a.qa++;b=new H(g,b,c,d,e,f,!a.A);if(h)return h.open("POST",a.D+"?seq="+g,!1),h.send(mb(b)),200==h.status;if(h=a.A)h.send(mb(b));else try{a.da.postMessage(lb(b))}catch(l){return a.N(),!1}d&1&&(a.R[g]=b);return!0}
function Fb(a,b){if(b.a){var c=b.a[1]||b.a[6],d=a.g[c];if(d)return d.b?b.b=d.port.id:null;d=a.i;for(var e in d)if(d[e].f==c)return b.b=e}e=b[6];d=b[17];var f=b[50],h=b[7],g=a.L,l=a.f;a=a.a;var k;if((k=g[e])||(k=g[d]))return b.b=k.id;if(k=g[f])var m=k.id;for(c in l){g=l[c];var p=g.f;if(p){if(p==e||p==d||p==f){k=g.port;if(h){var q=a[k.tabId];q&&q.o!=h&&(k=null)}if(k)return b.b=k.id}if(p==h)var r=g.port.id}}return m?b.b=m:r?b.b=r:null}
n.Ua=J[J.length]=function Gb(a,b,c,d){var f;a:for(;!c;){if(f=a.b)return f;if(a.a){var h=this.a[a.a[6]+","+a.a[7]];h?f=h.id:(h=a.a[7])&&this.i[h]&&(f=h)}if(f||(f=Fb(this,a)))break;var g=this.i,l=a[50],k=a[7],m;for(m in g){h=g[m];if(h.o==l){f=m;break a}h.o==k&&(f=m)}if(f)break;return k?browser.tabs.query({url:k},Gb.bind(this,a,b,!0)):null}return c?(browser.runtime.lastError,d&&(d=d.shift())&&(h=this.a[d.id])&&(f=a.b=h.id),b&&b(f)):a.b=f};
n.Ea=J[J.length]=function Hb(a,b,c){var e=a.tabId,f=a.X;if(b)if(ba(c))for(var h=a.o,g=h.includes("#")&&Ib(h),l=c.length;l--;){b=c[l];var k=b.frameId;if(k!=f)if(k&&!b.Qb&&(b.url==h||g&&b.url==g))f=a.X=k;else continue;var m=b.parentFrameId;break}else c?m=c.parentFrameId:browser.runtime.lastError;else if(0<f?!a.c:null==f){if(f&&822083584<=y)return browser.webNavigation.getFrame({frameId:f,tabId:e},Hb.bind(this,a,!0));if(f||a.o)return browser.webNavigation.getAllFrames({tabId:e},Hb.bind(this,a,!0))}0<=
m&&(a.c=e+","+m);if(null!=f&&a.j){if(b=this.s[e+","+f])a.f=b.g,a.m=b.f,a.h=b.h,a.v=b.b,(c=b.Y)&&a.o!=c&&(a.Y=c),a.c||(a.c=b.c),(c=this.g[a.f])&&!c.port&&(c.port=a);this.a[e+","+f]=a;e=[11,e,f,a.h,a.m,this.ta];(f=a.l)&&a.m&&(c=this.G[f],m=cb[f],e.push(f),fa(e,m.map(Jb(c)).map(Kb)));a.postMessage(e)}};
n.ia=J[J.length]=function Lb(a,b,c,d,e,f,h,g){var k=Mb(a,!0);if(!k)return 0;if(1==k){if(!h)return P(a,Lb.bind(this,a,b,c,d,e,f,!0)),-1;N(g)&&(g=Q(g))}h=[k];var m={};m[6]=Ib(a,1==k);m[50]=b;m[7]=c;m[8]=d;m[100]=e;m[102]=f;m[51]=g;m[54]=navigator.userAgent;m[121]=x?this.H:this.m;O(this,14,1,0,h,m);return 3};
n.Eb=J[J.length]=function Nb(a,b,c,d,e,f){if(c){var g=c.b;var l=c.H;var k=c.j}if(!d){if(!a||!a.length)return;f=Ob();g&&!l&&P(g,e=R());for(var m of a)P(m[0],f[f.length]=R());return S(Nb,this,a,b,c,!0,e,f)}e&&(l=Q(e));for(m of a)m[5]=Q(f.shift());b=0;c=[0];d={8:4};d[54]=navigator.userAgent;d[7]=g;d[110]=k;d[111]=l;d[121]=x?this.H:this.m;1<a.length&&(O(this,15,1,0,[a.length],d),b=16,d={});for(m of a)d[6]=m[0],d[100]=m[2],d[102]=m[3],d[50]=m[4],d[51]=m[5],O(this,14,1,b,c,d)};
function Pb(a,b,c,d,e,f,h,g){if(!d||a.c[-8]){var l=a.a[b];if(l){var k=Ab(a);k.tabId=b;k.port=l;k.D=c;k.count=0;k.c=[];if(l=d&&!!e)k.B=!0,k.G=e,k.s=f,k.v=h,k.m=g,e.b||Qb(a,e);e=k.a;(d=d&&a.c[12])?(d=d.replace(/\./g,"\\.").replace(/\*/g,".*").replace(/~/g,"(?:.*\\.)?"),d="^(?:http|https|ftp|ftps)://(?:[^\\/]*@)?(?:"+d+")(?::\\d+)?(?:\\W|$)"):d="^(?:http|https|ftp|ftps)://";k.f=Rb(a,b,[12,e,c,l,d]);k.C=0;k.f||Bb(a,k)}}}
n.Bb=function(a,b,c,d,e,f,h,g){if(a=this.B[b]){d&&(a.count+=d);h&&(a.b=h);g&&(a.j=g);if(e&&("string"==typeof e&&(e=JSON.parse(e)),e instanceof Array)){if(f)for(var l of e)l[4]=f;fa(a.c,e)}++a.C<a.f||(a.B?(d=a.tabId,(e=this.b[a.port.a])&&e.u==d&&a.count&&(f=a.m,h=e.g,g=e.c,O(this,10,1,0,[4294967295,e.H,Math.round(a.s*f+(e.i+h)*g),Math.round(a.v*f+(e.G+h)*g),0,a.count]),this.j=d,Rb(this,d,[13,!0]))):(d=a.c,d.length?this.Eb(d,a.D,a):Sb(a.tabId,"cannot_find_links")),Bb(this,a))}};
n.hb=function(a,b,c,d){if(a=this.B[b])this.ia(a.i,a.l,a.b,a.h,c,d),Bb(this,a)};n.kb=function(a,b,c,d,e,f){this.ja(a,b,c,d);a=[b,a.tabId,a.f,a.l];b={};b[132]=d;b[134]=e;b[133]=f;O(this,23,1,0,a,b)};n.W=J[J.length]=function Tb(a,b,c){if(4294967295==a)this.j=null,c=!0;else{var e=this.f[a];if(e){c=e.a;if(!c)return;if(b)switch(c){case 3:return;case 2:break;default:e.a=3;window.setTimeout(Tb.bind(this,a,!1,!0),1E3);return}e.a=0;c=!0}}c&&O(this,8,1,32,[a])};
n.Kb=function(a,b,c,d,e,f,h,g,l){var k=a.tabId,m=a.a,p=this.b[m],q=this.h[k];if(b){var r=this.B[b],B=r&&r.A;if(B){if(!c&&a.v){var C=this.a[a.c];if(C)return C.postMessage([15,b,null,B[6],B[17],B[50],B[31],B[133]])}var z;if(!d){if(!c||null==e){if(!a.b){c=a.ea;f="iframe";h=a.o;var v=!!c}if(!v){c=k;f=h=null;var A=!0}}a=this.ja(a,c,f,h);p=k==p.u&&!p.a&&(A||v||e)&&!q;!p||A||a.a||window.setTimeout(this.Z.bind(this,m),3E3);var M=2;a.a=p?1:2;var E=(p?128:64)|(A?512:0);!g&&(z=this.a[k])&&(g=z.D)}T(this,B,M||
1,E||0,m,k,c,g,l);!M||A||q||Ub(this,c,e);Bb(this,r)}}else d?(this.W(c,!0),delete this.f[c]):k!=p.u||p.a||q||(e?Ub(this,c,e,!0):Vb(this,c))};function Wb(a,b){var c=a.b[b];if(c&&c.f){var d=c.g,e=c.c;O(a,7,2,c.a?128:c.C?256:c.h?512:0,[b,Math.round((c.i+d)*e),Math.round((c.G+d)*e),Math.round((c.width-d-c.D)*e),Math.round((c.height-d)*e)])}}
function Ub(a,b,c,d){var e=a.f[b];if(e&&e.a){var f=e.port,h,g=256;2==e.a&&(null==d&&(h=a.b[f.a])&&(d=f.tabId==h.u&&!h.a),d?(g|=128,e.a=1):g|=64);(d=e.c)&&!c&&(c=f.i);if(c){var l=c[0];var k=c[1];var m=c[2]||l+1;var p=c[3]||k+1;var q=c[4];if(c=!d&&f.i)l+=c[0],k+=c[1],m=Math.min(m+c[0],c[2]),p=Math.min(p+c[1],c[3]);if(f=a.a[f.tabId])var r=f.B}O(a,9,1,g,[b,l,k,m,p,q,r])}}
n.Z=function(a){var b=this.h,c=[],d={};if(a){var e=this.b[a];e&&(e.a||e.b||b[e.u]||c.push(e.u))}else for(e of U(this.b))e.a||e.b||b[e.u]||c.push(e.u);if(c.length)for(var f of U(this.f))a=f.port,f.a&&c.includes(a.tabId)&&((b=this.a[a.tabId])&&b.g&&(b.g=!1,b.postMessage([14,!1])),f.b?a.b?a.postMessage([15,null,f.id]):Qb(this,a,null,d):Ub(this,f.id,null,!0))};function Xb(a,b){var c=a.b,d;if(b=null==b?U(c):(d=c[b])?[d]:null)for(d of b)K(a,d.u,void 0)}
function K(a,b,c,d){d=0!=d;var e=c?0:2;c=c?32:64;var f=a.f,h;for(h in f){var g=f[h];g.a&&g.port.tabId==b&&g.a!=e&&(d||g.b)&&(g.a=e,O(a,8,1,c,[h]))}}function Vb(a,b){var c=a.f[b];c&&1==c.a&&(c.a=2,O(a,8,1,64,[b]))}function Yb(a,b,c,d){var e=a.ca,f=(e&b)!=((c?63:32)&b);a.ca=c?e|=b:e&=~b;f&&(c=a.c[-1],b=a.c[-2],c=a.ba=0!=c&&(e&c)==c,e=a.la=0!=b&&(e&b)==b,a.va=(c||e)&&d||null)}
n.Oa=J[J.length]=function Zb(a,b,c,d){var f=this.b[a];if(f)if(d)f.m|=b,f.s|=c,f.b&&window.clearTimeout(f.b),f.b=window.setTimeout(Zb.bind(this,a),d);else{b|=f.m;c|=f.s;f.m=f.s=f.b=null;if(b){for(var h of U(this.i))h.b&&h.a==a&&(h.g=!0);browser.windows.get(a,this.O);browser.tabs.query({windowId:a,active:!0},this.O)}if(c){if((a=this.b[a])&&!a.b&&(a=a.u,!this.h[a])){b=this.f;for(var g in b)c=b[g],c.a&&c.port.tabId==a&&1==c.a&&O(this,8,1,1152,[g])}}else this.Z(a)}};
n.O=function(a,b){browser.runtime.lastError;a instanceof Array&&(a=a.shift());if(a){var c=a.windowId||a.id,d=this.b[c];if(d){if(a.windowId){d.u=a.id;if(d.j&&Sa(a.url))return;a.width&&(d.B=a.width);a.height&&(d.A=a.height)}else{var e=b?d.c=this.ka:d.c,f="fullscreen"==a.state,h=!b&&f!=d.a;d.a=f;d.C="maximized"==a.state;d.h="minimized"==a.state;w?(d.width=Math.round(a.width/e),d.height=Math.round(a.height/e),d.l=Math.round(a.left/e),d.v=Math.round(a.top/e)):(d.width=a.width,d.height=a.height,d.l=a.left,
d.v=a.top);h&&(f?Xb(this,c):this.Z(c))}f=d.B;a=d.A;if(f&&a){h=d.width;e=d.height;if(!d.j&&!d.h){if(f>h||a>e)return browser.windows.get(c,this.O);d.j=!0}f=h-f;h=f/2;0<=h&&16>=h?(d.g=h,d.i=d.D=0):(h=d.g,x||ja?d.i=f-2*h:d.D=f-2*h);a=e-a-2*h;a<=qa&&(d.G=a)}b||Wb(this,c);return d}}};function sb(a,b){return a.h[b]?!0:(a=a.a[b])&&a.h?(a.h=!1,browser.tabs.reload(b),!0):!1}n.Hb=function(a,b,c,d){a.o=b;a.A=c;a.h&&!d&&(a.h=!1);null==a.X&&this.Ea(a);this.Z(a.a)};
n.Jb=function(a,b,c,d,e){a.D=b;a.B=e;a=[a.f,a.tabId,a.a,d,e];d={};d[110]=b;d[128]=c;O(this,21,1,0,a,d)};
n.Lb=function(a,b,c,d,e){var f=a.tabId,h=this.a[f+","+c];if(h){var g=h.i;h.ea=d;if(h.i=e){var l=a.i;l&&(e[0]+=l[0],e[1]+=l[1],e[2]=Math.min(e[2]+l[0],l[2]),e[3]=Math.min(e[3]+l[1],l[3]));if(g&&g.join()!=e.join()){g=this.a;a=a.tabId+",";c=a+c;for(var k in g)k.startsWith(a)&&(l=g[k],l.c==c&&h.postMessage([16,b,l.X,l.ea]))}}if(!this.h[f]){Ub(this,d,e);for(var m of U(this.f))m.port==h&&m.a&&m.b&&!m.c&&h.postMessage([15,null,m.id])}}};
function Qb(a,b,c,d){a=a.a;c=[16,c];for(var e=[b],f;f=a[b.c];b=f){if(d)if(d[b.id])break;else d[b.id]=!0;e.push(f)}for(f=e.pop();b=e.pop();f=b)d=b.ea,c[2]=b.X,c[3]=d,c[4]=d?null:b.o,c[5]=d?null:b.Y,f.postMessage(c)}function Rb(a,b,c){a=a.a;b+=",";var d=0,e;for(e in a)e.startsWith(b)&&(a[e].postMessage(c),d++);return d}
n.ga=function(a,b){var c={file:"content.js",runAt:"document_start",matchAboutBlank:!0};b&&!w?c.frameId=b:c.allFrames=!0;if(a instanceof Array)for(;b=a.shift();)try{b.discarded||browser.tabs.executeScript(b.id,c,W)}catch(d){}else if(b=a)try{browser.tabs.executeScript(b.id||b,c,W)}catch(d){}};function $b(a,b,c,d){var e=17,f=[b.H,b.f,b.width,b.height,b.l,b.v,b.c],h={};b.C?e|=256:b.h&&(e|=512);null!=c&&(e|=c?2048:1024);d&&(h[117]=d);O(a,6,2,e,f,h)}
n.Pa=J[J.length]=function ac(a,b,c){if(b){a={};for(var e of c)a[e.windowId]=e.title;for(var f of b)b=this.O(f,!0)||this.Ma(f,!0),$b(this,b,f.focused,f.title||a[f.id])}else{if(!a){try{browser.windows.getAll({windowTypes:["normal","popup"]},b=R())}catch(h){browser.windows.getAll(b)}browser.tabs.query({active:!0},c=R());return S(ac,this,1,b,c)}if(w&&1==a&&c){b=Ob();for(f of c)browser.windows.get(f.windowId,b[b.length]=R());return S(ac,this,2,b,c)}}};
n.Gb=J[J.length]=function bc(a,b){if(void 0===a)return cc("system.display",bc.bind(this));if(a){if(!b)return browser.system.display.getInfo(null,bc.bind(this,a));this.Ca=b[0].displayZoomFactor}};
n.oa=function(a,b){if(!this.v)return Sb(b.id,"cannot_contact_idm");var c=a.linkUrl,d=a.pageUrl,e=d;if(a.menuItemId==this.P[4])return browser.downloads.search({query:[c]},this.Ra.bind(this,c));if(a.menuItemId==this.P[1])c=a.frameUrl,c&&"about:blank"!=c||(c=d,e=null);else if(!c&&(c=a.srcUrl,(a=this.a[b.id+","+a.frameId])&&c)){var f=Ab(this);f.tabId=b.id;f.port=a;f.i=c;f.l=e;f.b=d;f.h=4;return a.postMessage([18,f.a,c])}c&&this.ia(c,e,d,4)};
n.Da=function(a,b){if(!this.v)return Sb(b.id,"cannot_contact_idm");Pb(this,b.id,a.menuItemId==this.P[2])};n.Ra=function(a,b){for(var c,d,e;c=b.pop();)c.exists&&"complete"==c.state?d||e||(e=c.referrer):(d||(d=c.referrer),browser.downloads.erase({id:c.id}));this.ia(a,d||e,null,4)};
n.lb=function(a){var b=a.sender.tab;if(b&&!(0>b.id)){a.name=a.name.split(":").shift();var c=a.id;null==c&&(c=a.id=this.Ta++);var d=b.id,e="top"==a.name;a.tabId=d;a.a=0>b.index?null:b.windowId;a.j=!0;a.s=!1;a.g=e;a.b=e;a.X=e?0:a.sender.frameId;a.G=0;a.o=a.sender.url||e&&b.url||null;a.Y=null;this.i[c]=a;e&&(this.a[d]=a);a.o&&(a.l=Eb(this,(new URL(a.o)).hostname));a.onMessage.addListener(this.mb.bind(this,a));a.onDisconnect.addListener(this.ha);this.Ea(a)}};
n.ha=function(a,b){browser.runtime.lastError;if(a.j){a.j=!1;var c=a.tabId+","+a.X,d=this.B,e=this.f,f,h=this.L,g=this.g,l,k;for(k in d)d[k].port===a&&delete d[k];for(k in e)if(f=e[k],f.port===a)this.W(k),delete e[k];for(var m in h)h[m]===a&&delete h[m];for(k in g)(l=g[k],l.port!==a||l.g)||delete g[k];this.va===a&&Yb(this,63,!1);delete this.i[a.id];delete this.a[c];a.b&&delete this.a[a.tabId];if(w&&!b)browser.tabs.executeScript(a.tabId,{code:"__idm_connect__ && __idm_connect__(); true;"},W);else for(k in a=
this.s,a)c==a[k].c&&delete a[k]}};
n.mb=function(a,b){var c=b[0];b[0]=a;switch(c){case 21:this.Hb.apply(this,b);break;case 24:this.Jb.apply(this,b);break;case 22:this.Lb.apply(this,b);break;case 23:this.Kb.apply(this,b);break;case 41:this.kb.apply(this,b);break;case 25:this.ja.apply(this,b);break;case 26:Pb(this,a.tabId,!0,!0,a,b[1],b[2],b[3]);break;case 27:this.Bb.apply(this,b);break;case 28:this.W(4294967295);break;case 29:this.Ha.apply(this,b);break;case 30:this.Ha.apply(this,b);break;case 31:this.fb.apply(this,b);break;case 32:this.ib.apply(this,
b);break;case 39:this.gb.apply(this,b);break;case 33:this.ab.apply(this,b);break;case 34:this.eb.apply(this,b);break;case 35:this.hb.apply(this,b);break;case 36:this.Ab.apply(this,b);break;case 37:this.ob.apply(this,b)}};
n.Ia=function(a){var b=a.type,c=a.m,d=a.l,e=a.a,f;if(1==b){var h=e[0];if(f=this.R[h])b=f.type,delete this.R[h]}switch(b){case 3:0<=this.S&&(this.S=-1,this.za());d=e[0];this.wa=9>d;this.sa=10<=d;this.$=e[6];if(d=e[4])d/=96,this.ka=u&&1.245>d?1:d,this.Pa(),u&&this.Ca&&this.Gb();dc(this,e[5],a);this.ma&&this.Aa();break;case 4:f=this.c;this.l=!!(e[3]&2147483648);this.ta=!!(e[3]&1073741824);dc(this,e[2],a);f[-9]=0<(d&64);f[-13]=0<(d&1024)||Na;f[-8]=0<(d&32);f[-4]=0<(d&2);f[-11]=0<(d&256)||2>c;f[-12]=0<
(d&512)||2>c;f[-1]=e[0];f[-2]=e[1];f[12]=a[12];f[17]=a[17];X(f,a,1);X(f,a,2);X(f,a,3);X(f,a,4);X(f,a,10);X(f,a,9,2);X(f,a,11,2);X(f,a,20);X(f,a,21,1);ec(f,a,19);ec(f,a,18,1,1);pb(this);this.M||(this.M=!0,u&&browser.browserAction.enable(),this.I(1,browser.runtime.onConnect,this.lb),u&&this.I(1,browser.proxy.settings.onChange,this.Ka),u&&browser.proxy.settings.get({},this.Ka),this.I(1,browser.webNavigation.onCreatedNavigationTarget,this.jb),this.I(1,browser.webNavigation.onCommitted,this.Ja),this.I(1,
browser.webNavigation.onHistoryStateUpdated,this.bb),(a=this.c[17])&&this.I(2,browser.webRequest.onBeforeRequest,this.ub,{urls:a.split("|"),types:Aa},["blocking"]),tb(this,!0),browser.tabs.query({url:G},this.ga));break;case 18:d=e[0];if(6<d)break;e=bb[d];d=this.G[d];for(var g in a)(g=parseInt(g))&&(102==g||110<g&&150>g)&&(d[g]=e.includes(g)?RegExp(a[g]):a[g]);e=this.G.map(fc(102)).filter(aa);this.ua=RegExp("^https?://(?:"+e.join("|")+")","i");X(d,a,101,2);break;case 5:a=e[0];(e=this.b[a])?(d=0!=(d&
128),e.a!=d&&(e.a=d)&&Xb(this,a)):this.Na(a);break;case 6:if(d&4)break;a=f.a[0];e=e[1];if(d=this.b[a])d.f=e,Wb(this,a);break;case 8:a=e[0];e=d&32;if(4294967295==a)Rb(this,this.j,[13,!1]),this.j=null;else if(a=this.f[a])a.a=e?0:2;break;case 11:a=e[0];4294967295==a&&(Pb(this,this.j,!0,!0),this.j=null);break;case 12:try{var l=a.a[5],k=a[4];e=4==l?2:3;if((1==l||2==l)&&Fb(this,a)){if(this.c[3].test(k))1==l?e=6:l=4;else if(this.c[-4]||this.c[4].test(k))e=6;a[8]|=256}if(4==l)if(!this.wa||a.a[6]||a.a[7]){switch(a.a[4]){case 1:a[7]||
(a[7]=a[50]);break;case 3:a[7]||(a[7]=a[32]),a[50]||(a[50]=a[31])}this.Cb(a)}else T(this,a,1);else T(this,a,e)}catch(m){T(this,a,0)}break;case 13:a=f.a[0];d=f.a[5];e=e[1];g=3==e;if(3>=d)f.l&128?gc(this,a,g):Y(this,a,g);else if(5==d)if(e){if(a=(f=this.g[a])&&f.i){g=f.method;e=f.requestHeaders;if(d=f.f)(d=hc(d,Z(e,"Content-Type")))||(g="GET");a.timeout=1E4;a.onreadystatechange=this.nb.bind(this,a,f.id);a.open(g,f.url,!0);for(f=0;f<e.length;f++)g=e[f].name,c=g.toLowerCase(),c.startsWith("x-idm-")||(Ta(c)&&
(g="X-IDM-"+g),a.setRequestHeader(g,e[f].value));a.send(d)}}else ic(this,a);break;case 20:e=a[123];d=!e;a=[a.j,0,0,0];f={};x&&(g=this.H)&&(f[122]=g,d||(d=g.substr(2).split(";",1).shift()==e));f[121]=this.m;O(this,1,1,d?2:4,a,f);break;case 22:this.Qa(e[0],e[1],a[131],a[130]);break;case 1:break;default:!f&&d&1&&O(this,1,1,0,[a.j,0,0,0])}};
n.Qa=J[J.length]=function jc(a,b,c,d,e){if(!w&&null==Ra){if(void 0===e)return cc("notifications",jc.bind(this,a,b,c,d));Ra=e||!1}Ra&&(browser.notifications.create(a.toString(),{type:"basic",title:d||"",message:c,iconUrl:"images/logoSmall.png"},W),b&&window.setTimeout(browser.notifications.clear.bind(null,a.toString(),W),1E3*b))};
n.Cb=J[J.length]=function kc(a,b,c,d){try{var f=a.b;if(!f)if(c)f=a.b=c;else if(d){var h=this.b[d.id],g=this.a[h&&h.u];g&&(f=a.b=g.id)}else if(!b&&(f=this.Ua(a,c=R()),!f))return browser.windows.getLastFocused(d=R()),S(kc,this,a,!0,c,d);var l=this.i[f];if(!l)return T(this,a,0);(g=this.a[l.tabId])&&g.g&&(g.g=!1,g.postMessage([14,!0]));var k=Ab(this),m=a.a[8],p=[15,k.a,m];k.A=a;m||(l.b||Qb(this,l,k.a),p.push(a[6],a[17],a[50],a[31],a[133]));l.postMessage(p)}catch(q){T(this,a,0)}};
function T(a,b,c,d,e,f,h,g,l){-1!=c&&(e=[b.j,c,e,h,f],f={},f[8]=b[8],g&&(f[101]=g,f[128]=l),O(a,1,2,d|(0==c?4:2),e,f))}n.jb=function(a){yb(this,a).a=!0;x&&browser.windows.get(a.windowId,this.O)};
n.Ja=function(a,b){var c=a.tabId,d=a.frameId,e=a.url,f=a.transitionType;f=f?f.endsWith("_subframe"):w&&0<d;var h=this.s[c+","+d];this.V!=c||Sa(e)||(this.V=null);if(!f&&this.h[c]){var g;if(g=h)g=h.j,g=e&&g&&(new URL(e)).hostname==(new URL(g)).hostname;rb(this,c,g)}h&&(h.j=e);if(g=this.a[c+","+d])if(this.j&&(a=this.b[g.a])&&a.u==this.j&&this.W(4294967295),b){if(e!=g.o){b=this.f;var l,k;for(k in b)if(l=b[k],l.port===g)2==g.l?Vb(this,k):(this.W(k),delete b[k]);g.G++;g.o=e;g.b&&(g.g=!0);g.postMessage([17,
!0])}}else this.ha(g,!0),f&&"about:blank"==g.o&&this.ga(c,d);else f&&"about:blank"==e?(yb(this,a),this.ga(c,d)):h&&h.a&&(h.o||!b)&&(h.a=!1)};n.bb=function(a){return this.Ja(a,!0)};
n.Ma=function(a,b){var c=a.id;a={H:c,width:a.width,height:a.height,l:a.left,v:a.top,c:this.ka,g:8,G:pa,i:0,D:0,K:"popup"==a.type,a:"fullscreen"==a.state,C:"maximized"==a.state,h:"minimized"==a.state,A:0,B:0,u:0,j:!x,f:null,b:null};Object.setPrototypeOf(a,kb.prototype);this.b[c]=a;b&&(browser.tabs.query({windowId:c,active:!0},this.O),browser.tabs.query({windowId:c,url:G},this.Ib),browser.tabs.query({windowId:c,url:G},this.ga));return a};n.Ib=function(a){for(var b of a)yb(this,0,!0,b.id,b.url)};
n.Na=function(a){O(this,5,1,32,[a]);delete this.b[a]};n.zb=function(a){if(0<a){var b=this.b[a];b&&(b.f||$b(this,b,!0),sb(this,b.u),w&&this.Oa(a,!1,!0,500))}};n.tb=function(a,b,c){var d=c.windowId,e=this.b[d];e&&(e.f||$b(this,e),e.u||this.O(c));"complete"==b.status&&(a=this.a[a])&&!a.s&&(a.s=!0,this.Z(d))};n.sb=function(a){var b=this.a,c=this.s,d=a+",";this.V==a&&(this.V=null);var e=b[a];e&&this.ha(e,!0);for(var f in b)f.startsWith(d)&&this.ha(b[f],!0);for(var h in c)h.startsWith(d)&&delete c[h];delete this.h[a]};
n.qb=function(a){this.ca=0;this.j&&this.W(4294967295);var b=a.windowId;a=a.tabId;var c=this.b[b];if(c){var d=c.u;c.u=a;this.V==d&&(this.V=null,window.setTimeout(browser.tabs.remove.bind(null,d),250));K(this,d);browser.tabs.get(a,this.O)}sb(this,a)||this.Z(b)};n.rb=function(a,b){b=b.newWindowId;var c=this.i,d;for(d in c)(d=c[d])&&d.tabId==a&&(d.a=b);K(this,a,!0)};
n.Ha=function(a,b,c){if(a.b){var d=a.tabId;a=a.a;var e=this.b[a];this.j&&this.W(4294967295);if(e&&e.u==d){var f=!1;b&&(e.B=b,f=!0);c&&(e.A=c,f=!0);K(this,d,!1,f);this.Oa(a,f,!1,500)}}else a.ea&&(b=this.a[a.c])&&b.postMessage([16,null,a.X,a.ea])};n.fb=function(a,b,c){(b=db[b])&&Yb(this,b,c,a)};n.ib=function(a,b,c){0==b&&Yb(this,32,c,a)};n.gb=function(a,b,c){a.C=b;a.H=c};n.ab=function(){Yb(this,63,!1)};
n.eb=function(a,b,c,d){var e=a.f;e&&(a=32,c=[e,null==c?(a|=16,-2):c],e={},e[110]=b,e[115]=d,O(this,16,1,a,c,e))};n.Ab=function(a,b,c){if(a=this.g[b]){b=[b,0];var d={};d[115]=c;O(this,16,1,48,b,d);a.l=!1;a.S&&Y(this,a)}};n.ob=function(a,b,c,d){O(this,19,2,0,[b,c,a.tabId,a.f],d)};function ic(a,b){if(b=a.g[b]){var c=b.i;b.l=!1;b.i=null;b.S&&Y(a,b);c&&c.abort()}}n.nb=function(a,b){if(4==a.readyState){var c=[b,0],d={};200==a.status&&(d[115]=a.response);O(this,16,1,48,c,d);ic(this,b)}};
function lc(a,b){var c=a.c;if(b.m||a.h[b.tabId]||!c[-9])return 1;if(b.h)return 6;if(b.b&&c[-4])return 1;var d=b.L,e=b.M=mc(d.pathname);return c[9].test(d.hostname)||c[19].test(d.href)?1:2==(b.a&7)&&(b.G||c[-13])?d.pathname.endsWith("/")||c[21].test(d.pathname)?1:c[1].test(e)||a.l&&!c[20].test(e)?4:1:6}
function nc(a,b){if(b.c)return 6;if(b.h)return 3;var c=a.c,d=c[18],e=c[1],f=b.L,h=b.M,g=f.search?null:h,l=b.b,k=Ba.includes(b.type),m=!b.G,p=!k&&d.exec(f.href);if(p){var q=d.Mb,r=d.Nb,B=d.Ob,C=d.Pb;for(d=1;d<p.length;++d)if(p[d]){q=q[--d];if(null===q)break;p=0;var z=q.includes("V")|q.includes("A")|q.includes("C");if(l&&!z&&!q.includes("S")||m&&q.includes("D"))return 1;if(q.includes("G")){var v=!0;p|="GET"==b.method}q.includes("P")&&(v=!0,p|="POST"==b.method);if(v&&!p)break;if(p=C[d]){p=p.exec(f.href);
if(!p)break;f=r[d];if(r=f.F){var A=!0;var M=p[r]}if(r=f.T){A=!0;var E=p[r]}}E||(E=mc(M)||q.includes("T")&&(A=!0,h)||B[d]);if(z)E&&(g=b.M=E),l||(l=b.b=!0);else if(E?e.test(E):!A)return b.K=16777216,4;break}}if(g&&(k&&c[2].test(g)||l&&c[4].test(g)))return 1;if((x||a.D)&&(b.G||c[-13])){if(l&&c[3].test(g))return 6;if((!l||a.l)&&g&&e.test(g))return b.K=8,4}return 6}
function oc(a,b){if(b.da)return a.aa(6,b),6;var c=b.statusCode;if(200!=c&&206!=c&&304!=c)return 1;var d=Z(b.responseHeaders,"Content-Type"),e=Z(b.responseHeaders,"Content-Disposition"),f=pc(d).toLowerCase(),h="attachment"==pc(e).toLowerCase();c=b.b;var g=b.s;if(b.ca=g&&!h&&"text/html"==f){if(b.g){var l=zb(a,b);l&&(l.f=!0);a.aa(5,b)}return 1}if(c?b.m:b.c)return 1;if(a.l&&g&&h)return 4;var k,m,p,q=a.c,r=b.L,B=r.hostname,C=r.pathname;e=(d=qc(e,"filename")||qc(d,"name"))&&mc(d);if(d)if(e){b.P=d;var z=
p=!0}else if(!c)return 1;p||(d=C.split("/").pop(),(e=b.M||mc(d))&&e.toLowerCase()==f.split("/").pop()&&(z=!0));if(!z){var v=q[10].test(f),A=fb[f];if(A)if(A=A.split("|"),e&&A.includes(e))z=!0;else if(c?!v:!e){z=!0;var M=v;e=A[0]}!z&&e&&(h&&g?z=!0:v?z=M=!0:A||Va(e)||(z=M=!0))}if(c){A=Eb(a,B);g=a.G[A];v=C+r.search;switch(A){case 1:if(g[111].test(v))var E=z=!0;else if(g[112].test(v))var V=!0;else if(g[115].test(v)&&"application/json"==f)var ra=!0;else if(g[113].test(v)&&"application/x-www-form-urlencoded"==
f||g[114].test(v)&&"video/vnd.mpeg.dash.mpd"==f)var ea=!0;break;case 2:(B=g[111].exec(v))&&(Ua(f)||"text/html"==f)?(f=B[1]&&g[112].exec(b.port.o))&&B[1]!=f[1]||(ea=!0):g[114].test(v)?ra=!0:h&&"image"==b.type&&"MP4"==e&&(m=!0);break;case 3:"M4S"==e&&(z=!0);B==g[111]&&g[112].test(C)&&Ua(f)&&(ea=!0);break;case 4:g[111].test(v)&&Ua(f)&&(ra=!0);break;case 5:g[111].test(v)&&"text/html"==f&&(ra=!0);break;case 6:g[111].test(v)&&(ea=!0)}z&&("M3U8"==e||"F4M"==e||a.sa&&"MPD"==e?ea=!0:"F4F"==e&&(d.endsWith("Seg1-Frag1")||
d.endsWith("Seg1-Frag2")||d.includes("Seg1-Frag2_"))&&(k=!0));"ASF"==e&&((f=Z(b.responseHeaders,"Content-Length"))&&102400>=parseInt(f)&&(m=!0),"DCLK-AdSvr"==Z(b.responseHeaders,"Server")&&(m=!0))}if(m)return 1;z&&(c&&q[3].test(e)?E=!0:c&&q[4].test(e)?b.c=!0:!b.c&&q[1].test(e)&&(l=!0));if(E){var Cb,Db;if(m=q[11])m.test(r.hostname)?E=!1:(Cb=a.a[b.tabId])&&(Db=Cb.o)&&m.test((new URL(Db)).hostname)&&(E=!1)}ea||k?"POST"!=b.method||b.f?(a=new XMLHttpRequest,a.responseType=k?"blob":"text",b.i=a,V=!0):V=
!1:ra&&(V=b.l=!0);if(!l&&!E&&!V)return 1;z&&(b.A=e);p&&(b.P=d);b.g|=V;b.K=E||V?256:16|(c?4096:0)|(M?8388608:0);return l?4:E?2:5}
n.aa=J[J.length]=function rc(a,b,c,d,e,f){var g=b.url,l=b.a||Mb(g),k=1==(l&7),m=b.requestHeaders;if(k&&!d&&!e&&(f=Z(m,"Cookie"),null==f))return P(g,rc.bind(this,a,b,c,d,!0)),!0;N(f)&&(f=Q(f));var p=b.id,q=b.port&&b.port.id,r=b.timeStamp,B=c?Math.floor(c.timeStamp-r):null,C=b.K,z=b.responseHeaders;e=b.U;var v=c&&c.ip;c=0;3==sc(v,".")?C|=33554432:2<sc(v,":")&&(C|=4194304);l&16&&(C|=2097152);"POST"==b.method&&(C|=512);4>a&&(x||d)&&(c|=1);b.g&&b.i&&(c|=1);b.g&&5!=a&&(c|=32);b.b&&(c|=16);b.s&&(c|=b.v?
2048:4096);l=[p,q,Math.floor(r/1E3),Math.floor(r%1E3*1E3),l&7,a,b.tabId,b.frameId];p={};p[6]=Ib(g,k&&4>a);p[17]=b.Y;p[4]=b.A;p[100]=b.P;p[8]=C;p[129]=B;p[122]=this.m;p[11]=tc(m);p[13]=tc(z);p[18]=tc(e);b.f&&(p[14]=hc(b.f,Z(m,"Content-Type")));b.H&&(p[19]=hc(b.H,Z(e,"Content-Type")));if(null==m){a=this.s;g=b.tabId+","+b.frameId;do g=(k=a[g])&&k.c,k=k&&k.o,"about:blank"==k&&(k=null);while(!k&&g);p[50]=k;p[51]=f;p[54]=navigator.userAgent}x&&(p[122]=ub(this,b.proxyInfo,Z(m,"Proxy-Authorization")),p[55]=
ub(this,b.$,Z(e,"Proxy-Authorization")));if(!b.ca||!b.v)if(b=this.a[b.tabId])p[7]=b.o;return O(this,13,1,c,l,p,d)};n.fa=J[J.length]=function uc(a,b,c,d,e){if(void 0===a)b.D=d,b.C=e,xb(this,b);else{d=this.D?new XMLHttpRequest:null;e=this.aa(a,b,c,d);d&&(e=(d=e&&parseInt(d.getResponseHeader("x-idm-status")))?3==d:this.aa(a,b,c));if(e)return Oa&&!c?void(b.B=!0):x?new Promise(uc.bind(this,void 0,b,null)):Y(this,b,!0);b.c=!0}};
function Y(a,b,c){var d=a.g,e;if(N(b)){var f=b;b=f.id}else if(!(f=d[b]))return;if(c){if(f.s||f.R){var h=0<f.statusCode||!f.requestHeaders,g=zb(a,f);g&&g.a&&f.v?browser.tabs.remove(f.tabId):u&&h&&!f.R?e={redirectUrl:"javascript:void(0)"}:w&&h?e={redirectUrl:vc(f,g)}:Qa&&h&&(e={redirectUrl:a.C||vc(f,g)})}e||(e={cancel:!0});f.B=!0}(a=f.D)&&void 0!==c&&(f.D=f.C=null,a(e||{}));if(c=f.C)f.D=f.C=null,c();if(f.i||f.l)return f.S=!0,e;delete d[b];w&&delete d[f.requestId];return e}
n.Xa=function(a){(this.l||a.byExtensionId)&&!this.la&&this.c[-9]&&Mb(a.finalUrl||a.url,!0)&&(this.K[a.id]=a,browser.downloads.pause(a.id,W))};
n.Ya=function(a,b){var c=a.id,d=this.K;if(!d[c])return!1;var e=this.c,f=a.finalUrl||(a.finalUrl=a.url),h=new URL(f),g=a.a=Mb(f,!0),l=a.A=mc(a.filename||h.pathname);if(!(a.h=this.ba)&&!this.l&&(!e[1].test(l)||e[9].test(h.hostname)||e[19].test(h.href)))return gc(this,c);a.Fb=b;d[c]=a;if(1==g){if(!a.referrer){b=this.i;c=this.b;for(var k in b)if(d=b[k],d.o==f&&(a.referrer=d.A,(e=c[d.a])&&e.u==d.tabId))break}var m;P(f,k=R());a.url==f||P(a.url,m=R());S(this.Ga,this,a,k,m);return a.Fa=!0}return this.Ga(a)};
n.Ga=function(a,b,c){var d=Date.now();d=[a.id,0,Math.floor(d/1E3),Math.floor(d%1E3*1E3),a.a,2];var e={};e[6]=Ib(a.finalUrl);e[4]=a.A;e[103]=a.totalBytes||null;e[100]=a.filename||null;e[127]=a.mime||null;e[8]=a.h?2048:0;e[50]=a.referrer||null;e[51]=Q(b);e[54]=navigator.userAgent;e[122]=this.m;a.finalUrl!=a.url&&(e[17]=Ib(a.url),e[56]=Q(c));return O(this,13,1,129,d,e)||gc(this,a.id)};
function gc(a,b,c){var d=a.K[b];if(d){if(c)return browser.downloads.cancel(b,W),!0;d.Fa&&(d.Fa=!1,d.Fb());browser.downloads.resume(b,W);delete a.K[b]}return!1}n.ub=function(a){var b=new URL(a.url);if(b.search.startsWith("?d=")){var c=this.a[a.tabId];this.ia("idmreg:"+b.href.substr(b.protocol.length),null,c&&c.o);Y(this,a.requestId);(b=zb(this,a))&&b.a&&"main_frame"==a.type&&browser.tabs.remove(a.tabId);return{redirectUrl:Ka+"?register=1"}}};
n.La=function(a){var b=a.type,c=a.tabId,d=a.frameId;if(!(na&&!Da.includes(b)||0>c&&0==d)){var e=a.url,f=a.method,h=Mb(e);if(h&&("GET"==f||"POST"==f)&&e!=this.C){var g=a.id=w?String(this.Va++):a.requestId;g=this.g[g];var l=this.la,k="POST"==f;f="image"==b;var m=u&&0>c&&"other"==b,p=!m&&0>c&&0>d,q=0<c&&b.endsWith("_frame");if((c=p?null:this.a[c+","+d])||q||p||m||g){x&&k&&g&&Za(g.statusCode)&&(a.method="GET",k=!1);q&&yb(this,a,!1);if(!l&&k&&a.requestBody){d=a.requestBody;if(k=d.raw)for(var r=0;r<k.length&&
(k[r].bytes||(k=null));r++);if(!(k||d.formData||u&&d.error))return}d=new URL(e);d.hash="";a.L=d;a.a=h;a.h=this.ba;a.m=l;a.v=q&&"main_frame"==b;a.s=q;a.R=m;a.ba=p;a.b=p||Ca.includes(b);a.c=f;a.g=this.ua.test(e);a.f=a.requestBody;a.port=c;a.G=h&8||(x?a.proxyInfo&&"https"==a.proxyInfo.type:this.U[h]);g&&(a.id=g.id,a.port=c=g.port,a.h=g.h,a.m=g.m,a.Y=g.Y||g.url,a.U=g.U||g.requestHeaders,a.H=g.H||g.f,x&&(a.$=g.$||g.proxyInfo));if(a.b&&!f){b=this.L;for(h=b.Db;30<=h.length;)delete b[h.shift()];b[e]=c;h.push(e)}switch(a.j=
lc(this,a)){case 1:a.c=!0;case 6:xb(this,a);break;case 4:return this.fa(1,a)}}}}};
n.vb=function(a){var b=this.g[a.requestId];if(b){var c=b.requestHeaders=a.requestHeaders;b.timeStamp=a.timeStamp;if(!b.B){if(b.ba&&!b.port&&(a=Z(c,"Referer")))for(var d of U(this.i))if(d.o==a){b.port=d;break}x&&b.proxyInfo&&ub(this,b.proxyInfo,Z(c,"Proxy-Authorization"),!0);if("POST"==b.method&&(!b.f||b.f.error&&0<Z(c,"Content-Length")))return Y(this,b);switch(b.j=nc(this,b)){case 1:b.c=!0;break;case 4:return this.fa(1,b);case 3:return this.fa(3,b)}}}else if(0>a.tabId&&"xmlhttprequest"==a.type&&(a.initiator?
a.initiator==La:a.originUrl?a.originUrl==Ma:1)){b=a.requestHeaders;c={};d=!1;for(a=0;a<b.length;a++){var e=b[a],f=e.name.toLowerCase();f.startsWith("x-idm-")?c[f.substr(6)]=d=!0:"origin"==f&&e.value==La&&(c[f]=d=!0)}if(d){for(a=0;a<b.length;a++)e=b[a],f=e.name.toLowerCase(),c[f]?b.splice(a--,1):f.startsWith("x-idm-")&&(e.name=e.name.substr(6));return{requestHeaders:b}}}};
n.xb=function(a){var b=this.g[a.requestId];if(b){var c=b.statusLine=a.statusLine,d=b.statusCode=a.statusCode||parseInt(c.split(" ",2).pop());if(b.B||204==d&&c.includes(" IDM "))return Y(this,b,!0);c=b.responseHeaders=a.responseHeaders;b.da=Ya(d);if("image"==b.type&&(d=Z(c,"Content-Type"))&&d.toLowerCase().startsWith("image"))return Y(this,b);"quic"==Z(c,"Client-Protocol")?b.a|=16:(d=Z(c,"Alternate-Protocol"))&&d.endsWith(":quic,p=0")&&"chunked"!=Z(c,"Transfer-Encoding")&&(b.a|=16);switch(b.j=oc(this,
b)){case 1:return Y(this,b);case 4:return this.fa(2,b,a);case 3:return this.fa(3,b,a)}if(b.l)return c.push({name:"X-IDM-Request-ID",value:b.id.toString()}),{responseHeaders:c}}};n.yb=function(a){var b=this.g[a.requestId];if(a.type.endsWith("_frame")&&(200==a.statusCode||304==a.statusCode)){var c=zb(this,a);c&&(c.o=a.url,c.Y=c.l)}b&&(2==b.j?this.aa(4,b,a):5==b.j&&this.aa(5,b,a),Y(this,b))};n.wb=function(a){Y(this,a.requestId)};
n.Aa=J[J.length]=function wc(a,b,c,d,e){var h=ia&&"llbjbkhnmlidjebalopleeepgdfgcpec"==browser.runtime.id&&"ngpampappnmepgilojfohadhhmbhlaek";if(!a)return this.ma=!1,browser.storage.local.get("version",b=R()),(x?1124073472<=y:w?1073741824<=y:1)&&browser.extension.isAllowedIncognitoAccess(c=R()),u&&browser.management.get("jeaohhlajejodfjadcponpnjgkiikocn",d=R()),ia&&browser.management.get(h||"llbjbkhnmlidjebalopleeepgdfgcpec",e=R()),S(wc,this,!0,b,c,d,e);N(d)&&d.enabled&&browser.management.setEnabled(d.id,
!1);N(e)&&e.enabled&&browser.management.setEnabled(h||browser.runtime.id,!1);N(b)&&(b=b.version||"");if((e=Ja.version||"")&&e!=b&&null!=b&&(browser.storage.local.set({version:e}),x||browser.storage.local.remove("disabled"),a=this.ya,d=this.xa,!b||!a||d)){e="current="+escape(e);b&&(e+="&previous="+escape(b));a&&(e+="&manager="+(a?[a>>24&255,a>>16&255,a>>8&255,a&255].join("."):""));d&&(e+="&update=1");null!=c&&!c&&(e+="&incognito=1");x&&(e+="&mzffox=1");ja&&(e+="&opera=1");if(w||ia)e+="&msedge=1";browser.tabs.create({url:browser.runtime.getURL("welcome.html?"+
e)},function(g){g&&(this.V=g.id)}.bind(this))}};function dc(a,b,c){null==b&&(b=(b=Ia.exec(c[13]))?b[1]<<24|b[2]<<16|b[3]<<8:0);a.ya=b||0;a.xa=102825984>b}function Sb(a,b){b=browser.i18n.getMessage(b);x?browser.tabs.executeScript(a,{code:'window.alert(unescape("'+escape(b)+'")); true;'},W):window.alert(b)}n.I=function(a,b,c){if(null!=b){var d=da(arguments);if(x||w)d[2]=function(){return c.apply(null,arguments)};this.ra.push(d);b.addListener.apply(b,d.slice(2))}};
n.Ba=function(){for(var a=arguments.length?da(arguments):null,b=this.ra,c=0;c<b.length;c++)if(!a||a.includes(b[c][0])){var d=b.splice(c--,1).pop(),e=d.splice(0,2).pop();w&&d.splice(1);e.removeListener.apply(e,d)}};function R(){function a(b){browser.runtime.lastError;a.a?a.a(b):a.c=b;a.b=!0}return a}R.prototype=Object.create(Function.prototype);function Ob(){var a=[];Object.setPrototypeOf(a,Ob.prototype);return a}Ob.prototype=Object.create(Array.prototype);
function S(a,b,c){if(this instanceof S){c instanceof Array||(c=da(arguments,2));for(var d=0,e=0,f=Function.prototype.bind.bind(this.g,this),h=0;h<c.length;h++){var g=c[h];if(g instanceof Function)g.b?(c[h]=g.c,e++):(g.a=f(h,null),d++);else if(g instanceof Ob)for(var l=0;l<g.length;l++){var k=g[l];k.b?(g[l]=k.c,e++):(k.a=f(h,l),d++)}}d?(this.c=a,this.f=b,this.a=c,this.b=d):e&&(this.h=e,a.apply(b,c))}else return d=new S(a,b,da(arguments,2)),d.b||d.h}
S.prototype.g=function(a,b,c){var d=this.a;if(null===b)for(var e=2;e<arguments.length;e++)d[a++]=arguments[e];else d[a][b]=c;0==--this.b&&(this.c.apply(this.f,d),delete this.c,delete this.f,delete this.a)};function sa(a){return browser.i18n.getMessage(a)||a}function Ib(a,b){var c=a.lastIndexOf("#");c>a.indexOf("?")&&"!"!=a[c+1]&&(a=a.substr(0,c));b&&!Wa(a)&&(a="idmfc"+a);return a}
function vc(a,b){var c=a.port;b=b&&!b.i;w&&(c&&a.url==c.C||(b=!1));return Ka+(b?"?back=1":"?host="+(new URL(c&&c.o||a.url)).hostname)}function P(a,b){w&&a.startsWith("ftp:")?b([]):(a={url:a},ma&&(a.firstPartyDomain=null),browser.cookies.getAll(a,b))}function Q(a){var b="";if(a&&a.length)for(var c=0;c<a.length;c++)b&&(b+="; "),b+=a[c].name,b+="=",b+=a[c].value;return b}
function tc(a){if(!a||!a.length)return null;var b=[],c;for(c of a)b.push(c.name,": "),null!=c.value?b.push(c.value):c.binaryValue&&b.push(new Uint8Array(c.binaryValue)),b.push("\n");return b}function Z(a,b){if(!a)return null;b=b.toLowerCase();for(var c of a)if(c.name.toLowerCase()==b){if(null!=c.value)return c.value;if(c.binaryValue)return String.fromCharCode.apply(null,c.binaryValue)}return null}
function qc(a,b){if(!a)return null;a=a.split(";");for(b=b.toLowerCase();a.length;){var c=a.shift(),d=c.indexOf("=");if(0<d){var e=c.slice(0,d).trim().toLowerCase(),f=e.endsWith("*");if(f)e=e.slice(0,-1).trimRight();else if(g)continue;if(e==b){c=c.substr(d+1).trim();d=c.length-1;if('"'==c[0]?'"'==c[d]:"'"==c[0]&&"'"==c[d])c=c.slice(1,d);if(f&&c.includes("'")){if(c=c.split("'",3),f=c.shift().toLowerCase(),(d="utf-8"==f||"utf8"==f)||!g){var h=unescape(c.pop());var g=f;if(d)break}}else h=unescape(c)}}else 0>
d&&null==h&&c.trim().toLowerCase()==b&&(h="")}return h}function pc(a){const b=/[;,]/;return a&&(a=a.split(b,1).shift().trim())&&!a.includes("=")&&unescape(a)||""}
function hc(a,b){var c=a.raw;if(c){var d=String.fromCharCode;a="";for(b=0;b<c.length;b++){var e=c[b].bytes;if(!e)return null;e=new Uint8Array(e);for(var f=e.length,h=0;h<f;h++)a+=d(e[h])}return a}c=a.formData;if(!c)return null;e=pc(b).toLowerCase();a=[];if(e&&"application/x-www-form-urlencoded"!=e)if("multipart/form-data"==e){(e=qc(b,"boundary"))||(e="----WebKitFormBoundary"+Math.random().toString(36).substr(2));for(d in c)for(f=c[d],b=0;b<f.length;b++)a.push("--",e,'\r\nContent-Disposition: form-data; name="',
d,'"\r\n\r\n',f[b]||"","\r\n");a.push("--",e,"--\r\n")}else return null;else for(d in c)for(f=c[d],d=d.split(" ").map(encodeURIComponent).join("+"),b=0;b<f.length;b++)a.length&&a.push("&"),a.push(d,"=",(f[b]||"").split(" ").map(encodeURIComponent).join("+"));return a.join("")}function mc(a){return(a=Ha.exec(a))?a.pop().toUpperCase():""}function Mb(a,b){a=a.split(":",1).shift().toLowerCase();a=eb[a]||0;return b?a&7:a}
function gb(a){for(var b=a.length,c=b,d=0;d<c;){var e=a.charCodeAt(d++);128<=e&&(2048<=e?(b+=2,e-55296&56320||d++):b++)}return b}
function xc(a,b){browser.runtime.lastError;if(void 0===a){b=navigator.userAgent;a=b.match(/\b(?!(?:Safari|Chrome|Gecko)\/)\w+\/(\d+)(?:.(\d+))?(?:.(\d+))?(?:.(\d+))?\b(?!.*[()])/);b=x?a:b.match(/\bChrome\/(\d+)\.(\d+)\.(\d+)\.(\d+)\b/);if(!b)return!1;y=b[1]<<24|b[2]<<22|b[3]<<8|b[4];la=b[0];D=a?a[0]:b[0];u&&navigator.brave&&(D=D.replace("Chrome/","Brave/"));browser.runtime.getBrowserInfo&&browser.runtime.getBrowserInfo(xc);try{x&&browser.privacy.websites.firstPartyIsolate.get({},xc)}catch(d){}a=browser.webRequest.ResourceType;
if(a){if(a.MEDIA){Da.push("media");Ca.push("media");var c=!0}if(a.OBJECT_SUBREQUEST||(na=x&&922746880>y))Da.push("object_subrequest"),Ca.push("object_subrequest")}u&&(c||Ca.push("other"));u&&browser.management.get("clhiejnehegdfknplplojohghjaklbae",xc.bind(this,{}))}else"version"in a?(b=a.version.split(/\D+/),y=b[0]<<24|b[1]<<22|b[2]<<8|b[3],la=D=a.name+"/"+a.version,Qa=939524096>y):"value"in a?ma=a.value:b&&(oa=!0,D=D&&D.replace("Chrome/","Epic/"));return!0}
function X(a,b,c,d){if(b=b[c]||void 0)try{b=b.replace(/^\|+|\|+(?=\||$)/g,"").replace(/\./g,"\\."),b=1==d?b.replace(/\?/g,"[^/\\\\]").replace(/(^|[^*])\*(?!\*)/g,"$1[^/\\\\]*").replace(/\*\*/g,".*?"):b.replace(/\?/g,".").replace(/\*/g,".*?"),2==d&&(b=b.replace(/~/g,"(?:\\b[^.]+\\.)?")),b=RegExp("^(?:"+b+")$",1==d?"":"i")}catch(e){b=null}a[c]=b||za}
function ec(a,b,c,d,e){b=b[c];var f=[],h=[],g=[],l=[];if(b)try{b=b.replace(/^\|+|\|+(?=\||$)/g,"").replace(/[.?+(){}[\]]/g,"\\$&").replace(/\*(?=[^:/|&]*:\/\/)/g,"\\w%%").replace(/(:\/\/[^:/]*?)~/g,"$1(?:\\b[^./]+\\.)?").replace(/\\\?(?=\||$)/g,"(?:$&.%%)?");if(d){for(var k=b.replace(/(^|\|)(?:([A-Z]+)?(?:#(\w+))?!)?[^|]+/g,"$1$2|$3").split("|");k.length;){var m=k.shift();f.push(Xa(m)?m:null);h.push(k.shift())}b=b.replace(/(^|\|)[\w#]+!/g,"$1")}if(e){k=b.replace(/(^|\|)(?:(?=[^|]+?<[A-Z]:.*?>)|[^|]+)/g,
"$1").split("|");m=/<([A-Z]):(.*?)>/g;for(var p={F:"[^/\\?#&;]%%",T:"[^/\\?#&;.]%%"},q,r=0;k.length;++r)if(q=k.shift()){for(var B={},C=["^"],z="",v,A=1;v=m.exec(q);++A)B[v[1]]=A++,z=RegExp.rightContext,C.push(RegExp.leftContext,"(",v[2].replace(/\*/g,p[v[1]]||".%%?"),")");C.push(z,"$");g[r]=B;l[r]=RegExp(C.join("").replace(/\*/g,".*?").replace(/%%/g,"*"))}b=b.replace(m,"(?:$2)")}b=b.replace(/\*/g,".%%?").replace(/%%/g,"*");b=d||e?RegExp("^(?:("+b.replace(/\|/g,")|(")+"))$"):RegExp("^(?:"+b+")$")}catch(M){b=
null}a[c]=b||(b=/(?!)/);d&&(b.Mb=f,b.Ob=h);e&&(b.Nb=g,b.Pb=l)}function sc(a,b){var c=0;if(a)for(var d=0;0<=(d=a.indexOf(b,d));d++,c++);return c}function Kb(a){return N(a)?a.source.replace("\\/","/"):a}function cc(a,b){b&&browser.runtime.lastError||browser.permissions.request({permissions:[a]},b)}function W(a){browser.runtime.lastError;a;!0}const Jb=Function.bind.bind(function(a){return this[a]}),fc=Function.bind.bind(function(a){return a&&a[this]});var N=Object.isExtensible;
try{N(null)}catch(a){N=function(b){return b instanceof Object}}var U=Object.values;U||(U=function(a){return Object.keys(a).map(Jb(a))});Array.prototype.fill||(Array.prototype.fill=function(a){for(var b=this.length;b--;this[b]=a);return this});
const wb=[[!0,-11,"menu_download_link","link,image,video",I.prototype.oa],[!0,-11,"menu_download_link","page,frame,editable",I.prototype.oa,Ga],[!0,-11,"menu_download_selected","selection",I.prototype.Da],[!0,-12,"menu_download_all","page,frame,editable",I.prototype.Da],[u,-11,"menu_download_item","link",I.prototype.oa,["chrome://downloads/*"]]];J.splice(0);xc()&&new I;
