var f;
if(!window.__idm_init__&&"html"==document.documentElement.localName){window.__idm_init__=!0;Array.prototype.includes||(Array.prototype.includes=function(b,a){return 0<=this.indexOf(b,a)});NodeList.prototype[Symbol.iterator]||(NodeList.prototype[Symbol.iterator]=Array.prototype[Symbol.iterator]);HTMLCollection.prototype[Symbol.iterator]||(HTMLCollection.prototype[Symbol.iterator]=Array.prototype[Symbol.iterator]);"undefined"==typeof browser&&(browser=chrome);navigator.userAgent.includes("Edge/");navigator.userAgent.includes("Firefox/");
navigator.userAgent.includes("OPR/");var r=Array.prototype.includes,v=Function.call.bind(Array.prototype.slice),z=Function.apply.bind(Array.prototype.push),A=Function.call.bind(Array.prototype.forEach),B={16:!0,17:!0,18:!0,45:!0,46:!0},D=r.bind(["video","audio","object","embed"]),E=/(?!)/,I=window.self===window.top,J=window.origin||document.origin||location.origin,K=location.host.split(".").splice(-2,1).shift().toLowerCase(),L=RegExp("^(?:\\(\\d+\\)\\s+)?(.+?)\\s+[-|@]+\\s*"+K+"$","i");function F(){I&&
(this.Ca=0);this.Ea=[];this.O=[];this.u={};this.ta();window.__idm_connect__=this.ta.bind(this,!0);this.b(1,window,"resize",this.ob);this.b(1,window,"scroll",this.pb);this.b(1,window,"blur",this.hb);this.b(1,window,"keydown",this.Aa,!0);this.b(1,window,"keyup",this.Aa,!0);this.b(1,window,"mousedown",this.jb,!0);this.b(1,window,"mouseup",this.lb,!0);this.b(1,window,"mousemove",this.kb,!0);this.b(1,window,"click",this.ib,!0);this.b(1,document,"beforeload",this.fb,!0);this.b(1,document,"DOMContentLoaded",
this.za);"interactive"!=document.readyState&&"complete"!=document.readyState||this.za()}f=F.prototype;f.f=0;f.g=0;f.Y=-1;f.Z=-1;f.Ga=1;f.c="";f.o="";f.na=E;f.ra=E;f.H=E;f.j={};f.oa=E;f.pa=E;f.qa=E;f.ga=E;f.aa=":root:empty";f.da=":root:empty";f.ca=":root:empty";f.F=":root:empty";f.ea=":root:empty";f.$=":root:empty";f.fa=":root:empty";f.G=0;f.ba=E;f.ia=E;f.ka=":root:empty";f.ha=":root:empty";f.ja=":root:empty";f.ma=E;f.la=":root:empty";f.ta=function(b){this.Ba(-1);this.a=b=browser.runtime.connect({name:(I?
"top":"sub")+(b?":retry":"")+("file:"==location.protocol?":file":"")});this.R=b.id||b.portId_||this.R||Math.ceil(1048575*Math.random());this.b(-1,b,"onMessage",this.nb);this.b(-1,b,"onDisconnect",this.mb)};f.mb=function(){browser.runtime.lastError;this.Ba();this.a=this.R=null;window.__idm_init__=!1;window.__idm_connect__=null};f.nb=function(b){switch(b.shift()){case 11:this.Qa.apply(this,b);break;case 17:this.Ra.apply(this,b);break;case 12:this.Sa.apply(this,b);break;case 13:this.Ka=b.shift();break;
case 14:this.Va.apply(this,b);break;case 15:this.Wa.apply(this,b);break;case 16:this.Xa.apply(this,b);break;case 18:this.Ua.apply(this,b)}};f.rb=function(b,a){switch(this.S=b){case 1:this.La=this.A=!0;this.c=a.shift()||"";this.na=RegExp(a.shift()||"(?!)");this.H=RegExp(a.shift()||"(?!)");this.j=(a.shift()||"").split(/[|:]/).reduce(M,{});this.oa=RegExp(a.shift()||"(?!)");this.pa=RegExp(a.shift()||"(?!)");this.qa=RegExp(a.shift()||"(?!)");this.ra=RegExp(a.shift()||"(?!)");break;case 2:this.A=!0;this.c=
a.shift()||"";this.o=a.shift()||"";this.ga=RegExp(a.shift()||"(?!)");this.aa=a.shift()||":root:empty";this.da=a.shift()||":root:empty";this.ca=a.shift()||":root:empty";this.F=a.shift()||":root:empty";this.ea=a.shift()||":root:empty";this.$=a.shift()||":root:empty";this.fa=a.shift()||":root:empty";this.G=a.shift()||0;a.shift();this.ba=RegExp(a.shift()||"(?!)");break;case 4:this.A=!0;this.c=a.shift()||"";this.o=a.shift()||"";this.ia=RegExp(a.shift()||"(?!)");this.ka=a.shift()||":root:empty";this.ha=
a.shift()||":root:empty";this.ja=a.shift()||":root:empty";break;case 3:this.ma=RegExp(a.shift()||"(?!)");break;case 5:this.A=!0,this.c=a.shift()||"",this.o=a.shift()||"(?!)",this.la=a.shift()||":root:empty"}this.c.startsWith("^/")&&(this.c="^(?:"+J.replace(/\./g,"\\.")+")?"+this.c.substr(1))};f.P=function(b){if(this.S&&this.D(arguments))switch(this.S){case 1:this.eb(b);break;case 2:this.$a(b);break;case 4:this.ab(b);break;case 3:this.cb(b);break;case 5:this.bb(b)}};f.s=function(){if(!this.Fa){this.Fa=
!0;this.b(2,window,"message",this.qb);var b=document.createElement("script");b.src=browser.extension.getURL("document.js");b.onload=b.remove.bind(b);document.head.appendChild(b)}};f.J=function(b){var a=this.a,c;for(c of document.getElementsByTagName("script"))!c.src&&b.test(c.innerText)&&a.postMessage([34,null,-1,c.outerHTML]);a.postMessage([34,this.l()])};f.qb=function(b){var a=b.data;if(Array.isArray(a)&&b.origin==J)switch(a[0]){case 1229212977:window.postMessage([1229212978,this.A,this.La,this.c,
this.o],"/");break;case 1229212979:this.a.postMessage([36,parseInt(a[1]),a[2]])}};f.M=function(){var b=window.devicePixelRatio,a=document.width,c=document.body.scrollWidth;a&&c&&(b=a==c?0:a/c);return b};f.C=function(b){try{var a=parseInt(b.getAttribute("__idm_id__"));a||(a=this.R<<10|this.Ga++,b.m=a,b.setAttribute("__idm_id__",a),this.u[a]=b);return a}catch(c){return null}};f.K=function(b){b.i&&(window.clearTimeout(b.i),b.i=null);b.a&&(b.a.disconnect(),b.a=null);this.h&&this.h.unobserve(b);delete this.u[b.m]};
f.sa=function(b,a,c){if(!b.hasAttribute("__idm_id__")){var e=this.C(b);if(e){(b.a=new MutationObserver(this.T.bind(this))).observe(b,{attributes:!0,attributeFilter:["style"]});this.h&&this.h.observe(b);var g=this.B(b);this.a.postMessage([41,e,b.localName,b.src||b.data,a,c,g])}}};f.Pa=function(b,a,c,e,g){var m,l;try{var k=0;var n=document.activeElement;n&&D(n.localName)||(n=document.elementFromPoint(this.Y,this.Z))&&!D(n.localName)&&(n=null);for(var d of document.querySelectorAll("video,audio,object,embed")){var h=
d.localName,p="object"==h||"embed"==h;if(p){var q=d.type.toLowerCase();if(q.startsWith("text/")||q.startsWith("image/"))continue;if("embed"==h&&"application/x-shockwave-flash"!=q)continue}if(g&&d.getAttribute("__idm_link__")==g){var t=d;break}var u=d.src||d.data;if(u)u!=b&&u!=a||(t=d);else if(!p)for(var N of d.getElementsByTagName("source"))if((u=N.src)&&(u==b||u==a)&&(t=d))break;if(t){var w=window.getComputedStyle(d);if("cover"==w.objectFit){var O=d;t=null;continue}break}if(!n&&!G)if(u&&(u==c||u==
e))var G=d;else if("video"!=h||!u.startsWith("data:audio/")){var x=d.clientWidth,y=d.clientHeight;if(x&&y){var H=d.getBoundingClientRect();if(!(0>=H.right+window.scrollX||0>=H.bottom+window.scrollY)&&(w=window.getComputedStyle(d),"cover"!=w.objectFit))if("hidden"==w.visibility)"video"!=h||l||(l=d);else{p=x*y;if(p>k&&1.35*x>y&&x<3*y){k=p;var P=d}m||(m=d)}}}}}catch(Q){}if(d=t||O||n||G||P||m||l)"embed"!=d.localName||d.clientWidth||d.clientHeight||(b=d.parentElement,"object"==b.localName&&(d=b)),this.C(d)?
(b=d.a=new MutationObserver(this.T.bind(this)),b.observe(d,{attributes:!0,attributeFilter:["style"]}),b.observe(d.parentNode,{childList:!0}),this.h&&this.h.observe(d)):d=null;return d};f.Oa=function(b,a,c){var e=null,g;for(g of document.getElementsByTagName("iframe")){try{var m=parseInt(g.getAttribute("__idm_frm__"))}catch(k){}if(m==b){e=g;break}if(!e){var l=g.src;!l||l!=a&&l!=c||(e=g)}}return e&&this.C(e)};f.B=function(b){var a=null;try{if("hidden"==window.getComputedStyle(b).visibility)return!1;
var c=b.getBoundingClientRect(),e=Math.round(c.width),g=Math.round(c.height);switch(b.localName){case "video":(b.videoWidth||b.hasAttribute("__idm_link__"))&&document.contains(b)&&(a=!1);if(15>e||10>g)return a;break;case "audio":if(!e&&!g)return a;var m=!0}var l=document.documentElement,k=l.scrollWidth||l.clientWidth,n=l.scrollHeight||l.clientHeight,d=Math.round(c.left)+b.clientLeft,h=Math.round(c.top)+b.clientTop;if(d>=k||h>=n||m&&!d&&!h)return a;0==d&&h==-n&&e==k&&g==n&&(h=0);a=[d,h,d+e,h+g,this.M()]}catch(p){}return a};
f.l=function(){var b=I?80:90;try{var a=window.top.document.title}catch(c){}a||(a=(a=document.head.querySelector('meta[property="og:title"]'))&&a.getAttribute("content"),b=70);a&&(a=a.replace(/^\(\d+\)/,"").replace(/[ \t\r\n\u25B6]+/g," "),a=new String(a.trim()),a.src=b);return a};f.Ta=function(){if(!document.elementsFromPoint)return 0;var b=document.documentElement,a=b.clientWidth||b.offsetWidth;b=(b.clientHeight||window.innerHeight)/4;var c=document.elementsFromPoint(0,0),e=0,g=0,m=0,l;for(l of c)if(l.offsetWidth>=
a){var k=window.getComputedStyle(l);.95<=k.opacity&&(c=k.zIndex,"fixed"==k.position?(k=l.offsetHeight+l.offsetTop,e<k&&k<b&&(e=k,g=c)):m<c&&(m=c))}g<m&&(e=0);return e};f.Qa=function(b,a,c,e,g,m){if(g){var l=document.createElement("script");l.src=browser.extension.getURL("debug.js");l.onload=l.remove.bind(l);document.head.appendChild(l)}if(a){this.Ca=a;try{window.frameElement&&window.frameElement.setAttribute("__idm_frm__",a)}catch(k){}}this.wa(c);this.Ja=e;m&&this.rb(m,v(arguments,6));"loading"==
document.readyState?this.V=!0:this.P()};f.Ra=function(b){this.W&&this.f&&(this.f=0,this.X=window.setTimeout(this.U.bind(this,!1),3E3));this.P(!0);b&&this.wa()};f.wa=function(b){if(this.D(arguments)){var a=[21,this.tb||location.href,document.referrer];b&&a.push(document.getElementsByTagName("video").length,document.getElementsByTagName("audio").length);this.a.postMessage(a)}};f.Va=function(b){var a=b?this.D(arguments):1;if(0<a||0>a&&1!=this.S){a=this.l();var c=this.M(),e=this.Ta();this.a.postMessage([24,
a,a&&a.src,c,e])}};f.Xa=function(b,a,c,e,g){c||(c=this.Oa(a,e,g));e=(e=c&&this.u[c])&&this.B(e);this.a.postMessage([22,b,a,c,e])};f.Ua=function(b,a){var c=document.getElementsByTagName("a"),e;for(e of c)try{if(e.href==a){var g=e.download||null;var m=e.innerText.trim()||e.title||null;break}}catch(l){}this.a.postMessage([35,b,g,m])};f.Wa=function(b,a,c,e,g,m,l){if(this.D(arguments)){var k=[23,b,a,!1],n,d,h;if(a)a&&((n=this.u[a])||(k[3]=!0));else{if(n=this.Pa(c,e,g,m,l)){if(d=n.getAttribute("operadetachedviewtitle"))var p=
130;k[2]=a=n.m;k[5]=n.localName;k[6]=n.src||n.data}!d&&(d=this.l())&&(p=d.src,(h=L.exec(d))&&(d=h[1]));k[7]=d;k[8]=p}n&&(d=this.B(n),null!=d||document.contains(n)?k[4]=d:(this.K(n),k[3]=!0));this.a.postMessage(k)}};f.Sa=function(b,a,c,e){var g=e?RegExp(e,"i"):null;e=this.va(document,g,a);var m=document.getElementsByTagName("iframe"),l;for(l of m)try{var k=l.contentDocument;k&&!l.src&&z(e,this.va(k,g,a))}catch(n){}b=[27,b,this.Ca,e.length];c||(b[4]=e,b[5]=location.href,I&&(b[6]=location.href,b[7]=
document.title));this.a.postMessage(b)};f.va=function(b,a,c){var e=[],g={},m="",l="",k=!c;if(c){var n=b.getSelection();if(!n||n.isCollapsed&&!n.toString().trim())return e}for(var d of b.getElementsByTagName("a"))if(k||n.containsNode(d,!0))try{var h=d.href;h&&!g[h]&&a.test(h)&&(g[h]=e.push([h,2,d.download||null,d.innerText.trim()||d.title]));c&&g[h]&&(m+=d.innerText,m+="\n")}catch(t){}for(d of b.getElementsByTagName("area"))if(k||n.containsNode(d,!0))try{(h=d.href)&&!g[h]&&a.test(h)&&(g[h]=e.push([h,
2,null,d.alt]))}catch(t){}if(k)for(d of b.getElementsByTagName("iframe"))try{(h=d.src)&&!g[h]&&a.test(h)&&(g[h]=e.push([h,4]))}catch(t){}var p=c&&n.toString();if(p){m=this.v(m);for(h of this.v(p))h&&!g[h]&&a.test(h)&&!m.includes(h)&&(g[h]=e.push([h,1]))}if(c)for(d of b.getElementsByTagName("textarea"))if(c=d.selectionStart,p=d.selectionEnd,(m=n.isCollapsed&&c<p)||n.containsNode(d,!0))try{var q=m?d.value.substring(c,p):d.value;for(h of this.v(q))h&&!g[h]&&a.test(h)&&(g[h]=e.push([h,1]))}catch(t){}if(k||
!e.length)for(d of b.getElementsByTagName("img"))if(k||n.containsNode(d,!0))try{(h=d.src)&&!g[h]&&a.test(h)&&(g[h]=e.push([h,3,null,"<<<=IDMTRANSMITIMGPREFIX=>>>"+d.alt])),k&&d.onclick&&(l+=d.onclick,l+="\n")}catch(t){}if(k){for(d of b.getElementsByTagName("script"))l+=d.innerText,l+="\n";if(l)for(h of this.v(l))h&&!g[h]&&a.test(h)&&(g[h]=e.push([h,5]))}return e};f.v=function(b){if(!this.Da){var a="\\b\\w+://(?:[%T]*(?::[%T]*)?@)?[%H.]+\\.[%H]+(?::\\d+)?(?:/(?:(?: +(?!\\w+:))?[%T/~;])*)?(?:\\?[%Q]*)?(?:#[%T]*)?".replace(/%\w/g,
function(e){return this[e]}.bind({"%H":"\\w\\-\u00a0-\ufeff","%T":"\\w\\-.+*()$!,%\u00a0-\ufeff","%Q":"^\\s\\[\\]{}()"}));this.Da=RegExp(a,"gi")}for(var c=[];a=this.Da.exec(b);)c.push(a.shift());return c};f.D=function(b){var a=this.f;a||(b=v(b&&b.callee?b:arguments),b.unshift(arguments.callee.caller),this.O.push(b));return a};f.za=function(b){try{var a=window.top.document.getElementsByTagName("title")[0]}catch(c){}this.f=b&&a?-1:1;a&&(b=this.W,b||(this.W=b=new MutationObserver(this.U.bind(this))),
b.observe(a,{childList:!0}));try{this.h=new ResizeObserver(this.T.bind(this))}catch(c){}this.V&&(this.V=!1,this.P());for(b=this.O;a=b.shift();)a.shift().apply(this,a)};f.T=function(b){for(var a of b)b=a.target,b.m&&(document.contains(b)?(b.i&&window.clearTimeout(b.i),b.i=window.setTimeout(this.gb.bind(this,b),200)):(this.a.postMessage([23,null,b.m,!0]),this.K(b)))};f.gb=function(b){b.i=null;var a=document.contains(b),c;a?c=this.B(b):this.K(b);this.a.postMessage([23,null,b.m,!a,c])};f.U=function(b){if(b)window.clearTimeout(this.X),
this.X=window.setTimeout(this.U.bind(this,!1),1E3);else{0>this.f?this.f=1:++this.f;for(var a=this.O;b=a.shift();)b.shift().apply(this,b)}};f.fb=function(b){var a=b.target,c=a.localName;D(c)&&b.url&&(a=this.C(a),this.a.postMessage([25,a,c,b.url]))};f.Aa=function(b){!b.repeat&&B[b.keyCode]&&this.a.postMessage([31,b.keyCode,"keydown"==b.type])};f.jb=function(b){this.Ka&&this.a.postMessage([28]);if(0==b.button){var a=b.view.getSelection();a&&a.isCollapsed&&!a.toString().trim()&&(this.g=1);this.a.postMessage([32,
b.button,!0])}};f.lb=function(b){if(0==b.button){this.Y=b.clientX;this.Z=b.clientY;this.a.postMessage([32,b.button,!1]);var a=b.view.getSelection();a&&this.g&&(this.g=a.isCollapsed&&!a.toString().trim()?0:2)&&this.a.postMessage([26,b.clientX,b.clientY,this.M()])}};f.kb=function(){2==this.g&&(this.g=0)};f.ib=function(b){b=b.target;"a"==b.localName&&this.a.postMessage([39,b.href,b.download])};f.pb=function(){this.a.postMessage([29])};f.ob=function(b){b=b.target;this.a.postMessage([30,b.innerWidth,b.innerHeight])};
f.hb=function(){this.g=0;this.a.postMessage([33])};f.b=function(b,a,c,e,g){var m=v(arguments);m[3]=e.bind(this);this.Ea.push(m);0>b?(a=a[c],a.addListener.apply(a,m.slice(3))):a.addEventListener.apply(a,m.slice(2))};f.Ba=function(b){for(var a=this.Ea,c=0;c<a.length;c++){var e=a[c][0];if(!b||b==e){var g=a.splice(c--,1).pop(),m=g.splice(0,2).pop();0>e?(m=m[g.shift()],m.removeListener.apply(m,g)):m.removeEventListener.apply(m,g)}}};f.eb=function(b){if(!b&&this.Ja){this.s();b=this.a;var a,c,e,g,m=0;for(k of document.getElementsByTagName("script")){if(k.src){if(g=
this.H.exec(k.src))m|=1,this.j[g[1]]?c=g[1]:a=k.src}else if(g=this.ra.exec(k.innerText))m|=2,this.j[g[1]]&&(e=parseInt(g[1],10));else if(this.na.test(k.innerText)){m|=4;var l=k.outerHTML}if(7==m)break}if(e||c){var k={};k[118]=e;k[124]=c;b.postMessage([37,1,2,k])}b.postMessage([34,this.l(),null,l]);a&&(l=new XMLHttpRequest,l.responseType="text",l.timeout=1E4,l.onreadystatechange=this.sb.bind(this,a,l),l.open("GET",a,!0),l.send())}};f.sb=function(b,a){if(4==a.readyState){var c=this.H.exec(b);if((b=
(b=this.oa.exec(a.response))&&parseInt(b[1]||b[2],10))&&(!this.j[b]||!this.j[c[1]])){var e=this.pa.exec(a.response);a=this.qa.exec(a.response);if(e&&a&&e[2]==a[1]){c=c&&c[1];var g={};g[118]=b;g[119]=e[0];g[120]=a[0];g[124]=c;this.a.postMessage([37,1,1,g])}}}};f.$a=function e(a,c){a?(c&&a.shift().disconnect(),this.L.disconnect(),this.ya.disconnect(),this.xa.clear(),this.N.clear()):(this.s(),this.J(this.ga),this.L=new MutationObserver(this.Na.bind(this)),this.ya=new MutationObserver(this.Ma.bind(this)),
this.xa=new Set,this.N=new Set);if(c=this.Ha=document.querySelector(this.da)){if(a=this.L,a.observe(c,{childList:!0}),!this.ua(c,!0)&&(c=c.querySelector(this.ea))){var g=C(c,this.F);g&&a.observe(c,{childList:!0});a.observe(g||c.parentNode,{childList:!0})}}else!a&&(c=document.querySelector(this.aa))&&(g=new MutationObserver(e.bind(this,a=[])),a.push(g),g.observe(c,{childList:!0}))};f.ua=function(a,c){var e=this.L,g=this.F,m=this.$,l=this.ya,k=this.xa,n=0,d;for(d of a.querySelectorAll(m))k.has(d)||
d.querySelector(m)||(k.add(d),l.observe(d,{childList:!0,subtree:!0}),c&&(a=C(d,g))&&(e.observe(a,{childList:!0}),n++),A(d.getElementsByTagName("video"),this.I.bind(this)));return n};f.Na=function(a){var c=this.Ha,e;for(e of a){a=c.isSameNode(e.target);for(var g of e.addedNodes)1==g.nodeType&&this.ua(g,a)}};f.Ma=function(a){var c=this.N,e=this.G,g;for(g of a)for(var m of g.addedNodes)if(1==m.nodeType)if(a=m.getElementsByTagName("video"),a.length)A(a,this.I.bind(this));else for(var l of c){a=l;for(var k=
e;a&&k--;a=a.parentNode);a&&a.contains(m)&&this.I(l)}};f.I=function(a){if(!a.hasAttribute("__idm_id__")){var c=this.N,e=this.G,g=r.bind(["div","span","a"]),m,l,k;for(l=a.parentNode;e--&&l&&g(l.localName);l=l.parentNode){var n=l;if("a"==l.firstChild.localName){var d=l.firstChild;break}var h=l.previousSibling;if(h&&"div"==h.localName){(k=l.getElementsByTagName("a")).length?d=k[0]:1<(k=h.getElementsByTagName("a")).length?d=k[k.length-1]:(h=l.nextSibling)&&"ul"==h.localName&&(k=h.getElementsByTagName("a")).length&&
(d=k[0]);break}}d?d=d.href:C(a,this.ca)?d=location.href:n&&1==(k=n.querySelectorAll(this.fa)).length&&(d=k[0].href);d||1==document.getElementsByTagName("video").length&&(m=this.ba.exec(location.href))&&(m=m[1]);d||m?(c.delete(a),a.setAttribute("__idm_link__",d||m),this.sa(a,m,d)):c.add(a)}};f.ab=function(a){if(!a){this.s();this.J(this.ia);a=new MutationObserver(this.Ya.bind(this));var c=this.Ia=document.querySelector(this.ka);a.observe(document.body,{childList:!0});c&&a.observe(c,{childList:!0})}};
f.Ya=function(a,c){var e=document.body,g=this.Ia,m=this.ha,l=this.ja,k;for(k of a){a=e.isSameNode(k.target);var n=g.isSameNode(k.target),d;for(d of k.addedNodes)if(1==d.nodeType){var h=a&&l||n&&m||null,p;if(p=h){var q=d;for(p=0;"<"==h[p];p++);for(q=q.querySelector(h.slice(p));q&&p--;q=q.parentNode);p=q}(h=p)&&c.observe(h,{childList:!0});A(d.getElementsByTagName("video"),this.Za.bind(this))}}};f.Za=function(a){var c=a.getAttribute("poster");c&&this.sa(a,null,c)};f.cb=function(a){a||this.J(this.ma)};
f.bb=function(a){if(!a){this.s();var c=document.querySelector(this.la);c&&(a=this.l(),c=c.outerHTML,this.a.postMessage([34,a,null,c.slice(0,c.indexOf(">")+1)]))}};function C(a,c){var e;for(e=0;"<"==c[e];e++);for(a=a.closest(c.slice(e));a&&e--;a=a.parentNode);return a}function M(a,c){c&&(a[c]=!0);return a}new F}!0;
